### ISSUE TITLE
Dockerhub support for Dashboard

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-docker#101]

**Comment by juzhiyuan** [comment]
Hi @totemofwolf, would you please publish the image to Dockerhub for Apache APISIX Dashboard?

**Comment by zhangguanzhang** [comment]
+1

**Comment by ChinaSilence** [comment]
+1

**Comment by juzhiyuan** [comment]
Hi @ChinaSilence, we just released 2.10.1, and the Docker image will be published this week.
