### ISSUE TITLE
failed to paa rse yaml config: failed to merge, path[etcd->timeout] expect: number, but got: string

### ISSUE THREAD

**Issue by ClementeGao** [apache/apisix-docker#122]
apisix配置文件
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for testt
.

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same  
etcd cluster.
    - "http://172.18.5.10:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30
dashboard配置文件

conf:
  listen:
    host: 0.0.0.0 # 允许外网访问
    #host: 127.0.0.1 # `manager api` listening ip or host name
    port: 9000 # `manager api` listening port
  etcd:
    endpoints: # supports defining multiple etcd host addresses for an etcd cluster
      - 172.18.5.10:2379
  log:
    error_log:
      level: warn # supports levels, lower to higher: debug, info, warn, error, panic, fatal
      file_path:
        logs/error.log # supports relative path, absolute path, standard output
        # such as: logs/error.log, /tmp/logs/error.log, /dev/stdout, /dev/stderr
authentication:
  secret:
    secret # secret for jwt token generation.
    # NOTE: Highly recommended to modify this value to protect `manager api`.
    # if it's default value, when `manager api` start , it will generate a random string to replace itt
.
  expire_time: 3600 # jwt token expire time, in second
  users:
    - username: admin # username and password for login `manager api`
      password: admin
    - username: user
      password: user
~                                                                                                     
~                                                                                                     
~                                                                                                     
~                                                                                                     
~                                                                                                     
"conf.yaml" 25L, 1026C

etcd docker-compose配置

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - /home/etcd/data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
      - "2380:2380/tcp"
    networks:
      apisix:
        ipv4_address: 172.18.5.10

docker-compse文件配置

services:
  apisix:
    image: apache/apisix:2.1-alpine
    # 官网 2.1-alpine 镜像存在ssl无法启动BUG，此处暂用2.0-alpine替代
    #image: apache/apisix:2.1-alpine
    restart: always
    volumes:
      - /home/apisix/logs:/usr/local/apisix/logs
      - /home/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      # 此处分别以80、443替换原配置文件中的9080、9443以便直接配置使用
      - "9080:9080/tcp"
      - "9443:9443/tcp"
      #- "9080:9080/tcp"
      #- "9443:9443/tcp"
    networks:
      apisix:
        ipv4_address: 172.18.5.11

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - /home/etcd/data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
      - "2380:2380/tcp"
    networks:
      apisix:
        ipv4_address: 172.18.5.10

  apisix-dashboard:
    image: apache/apisix-dashboard:2.3
    ports:
      - 9000:9000
    volumes:
      - /home/apisix/dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
      - /home/apisix/dashboard/logs:/usr/local/apisix-dashboard/logs
    networks:
      apisix:
        ipv4_address: 172.18.5.18

networks:

**Comment by tokers** [comment]
@ClementeGao Could you provide a minimal reproducible case?

**Comment by gxthrj** [comment]
@ClementeGao If you have solved this issue, Please add some describe here, Thanks~

**Comment by ClementeGao** [comment]
一定要检查下配置文件

**Comment by gxthrj** [comment]
> 一定要检查下配置文件

haha,It is a fair suggestion.
