### ISSUE TITLE
bug: ci failed

### ISSUE THREAD

**Issue by fukiki** [apache/apisix-docker#126]
CI is failed when merged commit 5b07a0c into `apache:master`

![image](https://user-images.githubusercontent.com/59835099/106592719-d1855300-658a-11eb-93e3-cb1eb6ff9cf2.png)

**Comment by fukiki** [comment]
fixed by https://github.com/apache/apisix-docker/pull/125

**Comment by tokers** [comment]
@fukiki Any remaining problems?

**Comment by fukiki** [comment]
> @fukiki Any remaining problems?

@tokers About ci, `apisix_all_in_one_ci.yaml` and `dashboard_all_in_one_ci.yaml` only execute in the push step, Is it necessary to also execute both scripts in the pull_request phase to avoid similar errors？

**Comment by tokers** [comment]
I think so, could you submit a PR to optimize this? Thanks!
