### ISSUE TITLE
feature request: build image with local code

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-docker#135]
Currently we could only build docker image for certain official branches (master/2.3/..) but not local code or branch from certain developers. 

Since there is a need to build docker image in PR with the newest code, to test how new changes work with docker, we need to also provide a method to build image with local code, but not using luarocks to build apisix.

**Comment by tokers** [comment]
@Yiyiyimu See the alpine-dev directory, does this dockerfile meet the requirements?

**Comment by Yiyiyimu** [comment]
> @Yiyiyimu See the alpine-dev directory, does this dockerfile meet the requirements?

Thanks for the suggestions! It seems alpine-dev is still used to build master image (which seems duplicate of alpine with tag master).

**Comment by tokers** [comment]
@Yiyiyimu If so, we'd better to maintain a Dockerfile for the sake of development.
