### ISSUE TITLE
add docs for apisix-docker

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-docker#144]
Hi, if we need docs for this repo? if yes, please refer to the structure of apisix-ingress-controller's doc[1].

Here[2] is one example:

![image](https://user-images.githubusercontent.com/2106987/109449694-0d291500-7a84-11eb-8e23-0dc8b08e3a8d.png)

[1] https://github.com/apache/apisix-ingress-controller/tree/master/docs
[2] http://apisix.apache.org/docs/ingress-controller/design

**Comment by starsz** [comment]
> Hi, if we need docs for this repo? if yes, please refer to the structure of apisix-ingress-controller's doc[1].

IMO, yes. And we should adjust the doc directory structure.
