### ISSUE TITLE
Replace `docker build` command with `make` command in README

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-docker#147]
After we refactor CI (#140) in this repo, we could build docker image more easily with make command. But the commands in README were not updated.

Another problem is that there are too many hardcoded `VERSION` in this repo, say we don't need a default one in `alpine/Dockerfile` when we tend to set `VERSION` each time we build image. We could also fix this problem at the same time.

**Comment by starsz** [comment]
> Another problem is that there are too many hardcoded VERSION in this repo, say we don't need a default one in alpine/Dockerfile when we tend to set VERSION each time we build image. We could also fix this problem at the same time.

Agree +1.
