### ISSUE TITLE
Use Github Actions to automate upload image to Dockerhub

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-docker#148]
Currently we need maintainers to upload release images to Dockerhub manually. Following https://docs.github.com/en/actions/guides/publishing-docker-images, we could find how to use GitHub actions to do the upload step, for example, triggered by release branch.

However, due to Apache rules, there are chances that we are not allowed to use Github Actions provided by docker. So we might need to use Docker API to write the auto-upload scripts.

**Comment by tokers** [comment]
That's a good idea but how to prevent our password from leaking.

**Comment by Yiyiyimu** [comment]
> That's a good idea but how to prevent our password from leaking.

As you could see in https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub, we could store the secrets in secret part in the repo, so we could use it as the environment variable in Actions.

**Comment by Yiyiyimu** [comment]
@ace03uec Thanks for the remind!
