### ISSUE TITLE
[DISCUSS]Link access log and error log to stdout and stderr

### ISSUE THREAD

**Issue by starsz** [apache/apisix-docker#149]
As @pahud suggested, we can link the access log and error log to stdout and stderr.

Like this:

```
ln -s /dev/stdout /usr/local/apisix/logs/access.log
ln -s /dev/stderr /usr/local/apisix/logs/error.log
```

Then we can get the log more conveniently.

@gxthrj @tokers @spacewander What's your opinion?

**Comment by tokers** [comment]
Somebody already suggested it but I cannot find the issue.

**Comment by pahud** [comment]
Nginx official dockerfile
 
 https://github.com/nginxinc/docker-nginx/blob/fa2213a76da35137a5aee565cef5095a209aeb3d/mainline/debian/Dockerfile#L100-L102
 
 OpenResty official dockerfile
 https://github.com/openresty/docker-openresty/blob/b464e27f22c7fad271c5822bd0812742223c9653/alpine/Dockerfile#L151-L152

**Comment by pahud** [comment]
I am working on this issue https://github.com/pahud/cdk-apisix/issues/67 and will need the upstream apisix docker container output its log to stdout and stderr just like Nginx and OpenResty.

**Comment by starsz** [comment]
@membphis What's your opinion?

**Comment by tokers** [comment]
> Containerized apps with docker are usually designed to send its logs to `stdout` and `stderr` and the docker log drivers will capture it and route to the external destinations. In AWS, the default log driver is [awslogs](https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_awslogs.html) which routes all the logs from `stdout` and `stderr` to Amazon CloudWatch Logs. It's also possible to run a sidecar container like `fluentd` or `fluentbit` as a log router to read the input from log files and send to external destinations.
> 
> For single user local development, we can simply tail the log with [docker log](https://docs.docker.com/config/containers/logging/dual-logging/) or `kubectl logs`, however, in cloud environment, we need log drivers and log routers to ship the logs out to a centralized logging system or data ingestion system for further analysis. And the first thing we need to do is to ensure all the app logs in container always go to stdout and stderr.

Cool, good to know that.

**Comment by starsz** [comment]
ping @gxthrj @membphis. I think it's time to make a decision.
I will vote for the add `ln` to dockerfile.

**Comment by tokers** [comment]
Agree to do that.

**Comment by gxthrj** [comment]
Agree +1

**Comment by membphis** [comment]
sorry for my late reply.

I was hesitant before, but after looking at other projects such as Nginx, I think this method is good.

https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L110-L111 

agree +1

let us do it.

**Comment by starsz** [comment]
Good. @pahud Can you create a PR for it? Thank you very much.

**Comment by pahud** [comment]
> Good. @pahud Can you create a PR for it? Thank you very much.

PR created https://github.com/apache/apisix-docker/pull/151

**Comment by spacewander** [comment]
Solved.
