### ISSUE TITLE
request help: image 2.2-alpine got falsely overwriten to `release/2.5`

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-docker#170]
Hi all

Thanks you for the quick response.  I just want to point out that I'm not using APISIX 2.5.  I'm using the docker image for APISIX /apache/apisix:2.2-alpine with the apache/apisix-dashboard:2.3 dashboard.

One thing that I've noticed is that the apache/apisix:2.2-alpine has been updated 10 days ago, so my question is has this image perhaps been erroneous updated ?

I've tracked down the intermittent nature of the issue:
Docker images that are working are apache/apisix:2.2-alpine (digest 186f0052e1191)
Docker images that are not working are apache/apisix:2.2-alpine (digest 22a167dfcf31e)

_Originally posted by @rdouman in https://github.com/apache/apisix/issues/4048#issuecomment-820361055_

**Comment by Yiyiyimu** [comment]
Checked and indeed it contains code from apisix release/2.5

**Comment by tokers** [comment]
Not sure about the real situation, Do you know this? @gxthrj

**Comment by Yiyiyimu** [comment]
ping @gxthrj

**Comment by gxthrj** [comment]
I also don’t know what happened. 
From the perspective of time, it should be when APISIX 2.5 was released. 2.2-alpine was also updated.
We must be careful when uploading images

I will re-build 2.2-alpine from APISIX tag 2.2.

**Comment by Yiyiyimu** [comment]
It got fixed right @gxthrj? I think it could be closed
