### ISSUE TITLE
docker compoest start image, but etcd start failed

### ISSUE THREAD

**Issue by younglifestyle** [apache/apisix-docker#171]
Error is this : 
![image](https://user-images.githubusercontent.com/19261307/117393586-08bb2580-af27-11eb-8229-3873252dfaca.png)

**Comment by Yiyiyimu** [comment]
Hi @younglifestyle could you please share your OS and docker version? This might be a good [reference](https://blog.csdn.net/grace_yi/article/details/80069990).

**Comment by younglifestyle** [comment]
win10 20H2，WSL2
Docker version 19.03.6, build 369ce74a3c

**Comment by Yiyiyimu** [comment]
Same version but could not reproduce the error. Have you tried to start etcd alone and see if there's still this error? Or do you have another etcd container running?

**Comment by anyeshe** [comment]
我也遇到了同样的问题，请问解决了吗？

**Comment by Yiyiyimu** [comment]
> 我也遇到了同样的问题，请问解决了吗？

Have you tried the methods provided above?

**Comment by anyeshe** [comment]
[root@localhost example]# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@localhost example]# setenforce 0
setenforce: SELinux is disabled
[root@localhost example]# docker-compose -f docker-compose-etcd.yml up
Creating example_etcd_1 ... done
Attaching to example_etcd_1
etcd_1  | etcd 06:05:09.97
etcd_1  | etcd 06:05:09.97 Welcome to the Bitnami etcd container
etcd_1  | etcd 06:05:09.97 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd_1  | etcd 06:05:09.97 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd_1  | etcd 06:05:09.98
etcd_1  | etcd 06:05:09.98 INFO  ==> ** Starting etcd setup **
etcd_1  | etcd 06:05:10.00 INFO  ==> Validating settings in ETCD_* env vars..
etcd_1  | etcd 06:05:10.00 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd_1  | etcd 06:05:10.15 INFO  ==> Initializing etcd
etcd_1  | etcd 06:05:10.16 INFO  ==> There is no data from previous deployments
etcd_1  | etcd 06:05:10.16 INFO  ==> ** etcd setup finished! **
etcd_1  |
etcd_1  | etcd 06:05:10.19 INFO  ==> ** Starting etcd **
etcd_1  | 2021-05-10 06:05:10.226899 I | pkg/flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
etcd_1  | 2021-05-10 06:05:10.227032 I | pkg/flags: recognized and used environment variable ETCD_AUTO_TLS=false
etcd_1  | 2021-05-10 06:05:10.227049 I | pkg/flags: recognized and used environment variable ETCD_CLIENT_CERT_AUTH=false
etcd_1  | 2021-05-10 06:05:10.227063 I | pkg/flags: recognized and used environment variable ETCD_DATA_DIR=/bitnami/etcd/data
etcd_1  | 2021-05-10 06:05:10.227085 I | pkg/flags: recognized and used environment variable ETCD_ENABLE_V2=true
etcd_1  | 2021-05-10 06:05:10.227119 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
etcd_1  | 2021-05-10 06:05:10.227131 I | pkg/flags: recognized and used environment variable ETCD_LOG_LEVEL=info
etcd_1  | 2021-05-10 06:05:10.227148 I | pkg/flags: recognized and used environment variable ETCD_PEER_AUTO_TLS=false
etcd_1  | 2021-05-10 06:05:10.227181 W | pkg/flags: unrecognized environment variable ETCD_TRUSTED_CA_FILE=
etcd_1  | 2021-05-10 06:05:10.227199 W | pkg/flags: unrecognized environment variable ETCD_LISTEN_PEER_URLS=
etcd_1  | 2021-05-10 06:05:10.227207 W | pkg/flags: unrecognized environment variable ETCD_ON_K8S=no
etcd_1  | 2021-05-10 06:05:10.227214 W | pkg/flags: unrecognized environment variable ETCD_SNAPSHOTS_DIR=/snapshots
etcd_1  | 2021-05-10 06:05:10.227223 W | pkg/flags: unrecognized environment variable ETCD_BIN_DIR=/opt/bitnami/etcd/sbin
etcd_1  | 2021-05-10 06:05:10.227230 W | pkg/flags: unrecognized environment variable ETCD_VOLUME_DIR=/bitnami/etcd
etcd_1  | 2021-05-10 06:05:10.227238 W | pkg/flags: unrecognized environment variable ETCD_INITIAL_CLUSTER_TOKEN=
etcd_1  | 2021-05-10 06:05:10.227245 W | pkg/flags: unrecognized environment variable ETCD_NAME=
etcd_1  | 2021-05-10 06:05:10.227252 W | pkg/flags: unrecognized environment variable ETCD_ROOT_PASSWORD=
etcd_1  | 2021-05-10 06:05:10.227262 W | pkg/flags: unrecognized environment variable ETCD_CLUSTER_DOMAIN=
etcd_1  | 2021-05-10 06:05:10.227269 W | pkg/flags: unrecognized environment variable ETCD_DISASTER_RECOVERY=no
etcd_1  | 2021-05-10 06:05:10.227277 W | pkg/flags: unrecognized environment variable ETCD_KEY_FILE=
etcd_1  | 2021-05-10 06:05:10.227289 W | pkg/flags: unrecognized environment variable ETCD_DAEMON_GROUP=etcd
etcd_1  | 2021-05-10 06:05:10.227296 W | pkg/flags: unrecognized environment variable ETCD_START_FROM_SNAPSHOT=no
etcd_1  | 2021-05-10 06:05:10.227304 W | pkg/flags: unrecognized environment variable ETCD_INIT_SNAPSHOT_FILENAME=
etcd_1  | 2021-05-10 06:05:10.227311 W | pkg/flags: unrecognized environment variable ETCD_INIT_SNAPSHOTS_DIR=/init-snapshot
etcd_1  | 2021-05-10 06:05:10.227318 W | pkg/flags: unrecognized environment variable ETCD_INITIAL_CLUSTER_STATE=
etcd_1  | 2021-05-10 06:05:10.227325 W | pkg/flags: unrecognized environment variable ETCD_BASE_DIR=/opt/bitnami/etcd
etcd_1  | 2021-05-10 06:05:10.227332 W | pkg/flags: unrecognized environment variable ETCD_INITIAL_CLUSTER=
etcd_1  | 2021-05-10 06:05:10.227339 W | pkg/flags: unrecognized environment variable ETCD_CERT_FILE=
etcd_1  | 2021-05-10 06:05:10.227346 W | pkg/flags: unrecognized environment variable ETCD_NEW_MEMBERS_ENV_FILE=/bitnami/etcd/data/new_member_envs
etcd_1  | 2021-05-10 06:05:10.227352 W | pkg/flags: unrecognized environment variable ETCD_DAEMON_USER=etcd
etcd_1  | 2021-05-10 06:05:10.227359 W | pkg/flags: unrecognized environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=
etcd_1  | [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
etcd_1  | 2021-05-10 06:05:10.227417 I | etcdmain: etcd Version: 3.4.15
etcd_1  | 2021-05-10 06:05:10.227455 I | etcdmain: Git SHA: aa7126864
etcd_1  | 2021-05-10 06:05:10.227462 I | etcdmain: Go Version: go1.12.17
etcd_1  | 2021-05-10 06:05:10.227468 I | etcdmain: Go OS/Arch: linux/amd64
etcd_1  | 2021-05-10 06:05:10.227476 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
etcd_1  | [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
etcd_1  | 2021-05-10 06:05:10.228607 I | embed: name = default
etcd_1  | 2021-05-10 06:05:10.228632 I | embed: data dir = /bitnami/etcd/data
etcd_1  | 2021-05-10 06:05:10.228641 I | embed: member dir = /bitnami/etcd/data/member
etcd_1  | 2021-05-10 06:05:10.228648 I | embed: heartbeat = 100ms
etcd_1  | 2021-05-10 06:05:10.228654 I | embed: election = 1000ms
etcd_1  | 2021-05-10 06:05:10.228660 I | embed: snapshot count = 100000
etcd_1  | 2021-05-10 06:05:10.228701 I | embed: advertise client URLs = http://0.0.0.0:2379
etcd_1  | 2021-05-10 06:05:10.228856 W | pkg/fileutil: check file permission: directory "/bitnami/etcd/data" exist, but the permission is "drwxrwxr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.
etcd_1  | 2021-05-10 06:05:10.228969 C | etcdmain: cannot access data directory: open /bitnami/etcd/data/.touch: permission denied
[root@localhost example]# docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
[root@localhost example]#

**Comment by Yiyiyimu** [comment]
have you tried to build with non-root user

**Comment by anyeshe** [comment]
> have you tried to build with non-root user

尝试过，也是同样的错误，我刚才尝试使用composer file文件中etcd的镜像仓库里的配置文件就没有问题，如下：
```
version: '2'

services:
  etcd:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  etcd_data:
    driver: local
```

我仿照着改成了下面的样子
```
  etcd:
    image: docker.io/bitnami/etcd:3
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:
```

完后一切就正常了，我觉得应该是下面两项配置有点问题
```
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
```
导致权限出错

**Comment by Yiyiyimu** [comment]
@younglifestyle could the method provide by @anyeshe fix your problem

**Comment by Yiyiyimu** [comment]
Hi @gxthrj could you have a look at this problem

**Comment by tokers** [comment]
@anyeshe As you use the bind mount, which inherits the permission on host machine, you should check the permission and the owner of the `./etcd_data` directory.

**Comment by younglifestyle** [comment]
> > > @younglifestyle could the method provide by @anyeshe fix your problem
> > 
> > 
> > I'll try now
> 
> failed. Etcd can't see the log. the configuration is here
> ![image](https://user-images.githubusercontent.com/19261307/117625348-8477d500-b1a8-11eb-9687-a60656395ada.png)

I modified etcd_data permission to 777,  it's running.

**Comment by tokers** [comment]
@younglifestyle `777` is so permissive and It's fine in a development environment, while when you deploy components in the production environment, make sure don't assign such permission to avoid security problems.

Now considering it was solved.

**Comment by yicongsong** [comment]
我也报错了,请问怎么解决的
