### ISSUE TITLE
dashboard image on docker hub have wrong tag

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-docker#177]
`latest` should be the latest release version, and `dev` should be the master branch, while it seems currently the tags got switched. @gxthrj 

![image](https://user-images.githubusercontent.com/34589752/119597724-9912ba80-bdaf-11eb-93e5-ba8b5727e0cb.png)

**Comment by gxthrj** [comment]
Let me HAL.

**Comment by gxthrj** [comment]
There are some error in build rules, I have fixed.

![image](https://user-images.githubusercontent.com/4413028/119641772-94e8aa80-be4c-11eb-8e77-a9661267b03e.png)

**Comment by gxthrj** [comment]
Make `dev` tag auto-build. But `latest` will push by CI.

**Comment by Yiyiyimu** [comment]
@gxthrj maybe we need to rebuild `latest` tag to `2.6`

**Comment by gxthrj** [comment]
latest have be re-pushed with 2.6.
