### ISSUE TITLE
The container of apisix-dashboard will never start success when use BRIDGE mode

### ISSUE THREAD

**Issue by forgaoqiang** [apache/apisix-docker#184]
Run apisix-dashboard with -p 9000:9000 will never start because the default config let 
dashboard try to connect Ectd from 127.0.0.1 ....

**Comment by tokers** [comment]
@forgaoqiang You should configure the correct ETCD address for apisix-dashboard or it indeed cannot work.

**Comment by forgaoqiang** [comment]
> @forgaoqiang You should configure the correct ETCD address for apisix-dashboard or indeed it cannot work.
