### ISSUE TITLE
etcdmain: cannot access data directory: mkdir /bitnami/etcd/data: permission denied

### ISSUE THREAD

**Issue by duandao1950** [apache/apisix-docker#192]
[root@localhost example]# docker version
Client: Docker Engine - Community
Version: 20.10.7
API version: 1.41
Go version: go1.13.15
Git commit: f0df350
Built: Wed Jun 2 11:58:10 2021
OS/Arch: linux/amd64
Context: default
Experimental: true

Server: Docker Engine - Community
Engine:
Version: 20.10.7
API version: 1.41 (minimum version 1.12)
Go version: go1.13.15
Git commit: b0f5bc3
Built: Wed Jun 2 11:56:35 2021
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.4.6
GitCommit: d71fcd7d8303cbf684402823e425e9dd2e99285d
runc:
Version: 1.0.0-rc95
GitCommit: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
docker-init:
Version: 0.19.0
GitCommit: de40ad0

-------------------------------------------------------------------------------------------

etcd_1 | 2021-07-01 11:57:38.007837 I | embed: advertise client URLs = http://0.0.0.0:2379
etcd_1 | 2021-07-01 11:57:38.007935 C | etcdmain: cannot access data directory: mkdir /bitnami/etcd/data: permission denied

-------------------------------------------------------------------------------------------

 etcd:
    image: bitnami/etcd:3.4.15
    user: root
    restart: always
    privileged: true
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

-------------------------------------------------------------------------------------------

please help!

**Comment by Yiyiyimu** [comment]
Change the permission of `/etcd_data` to 777 could fix the problem on my side. You could give it a try.

Since the original permission is already 775, do you have some other suggestions on the permission issue @tokers

**Comment by duandao1950** [comment]
fixed! thx.

step:
cd  apisix-docker/example/
this directory: chmod 777 etcd_data

**Comment by tokers** [comment]
@duandao1950 What is the owner and group and the permission for `./etcd_data`.

**Comment by lingsamuel** [comment]
Data directory should be owned by user `etcd` by default because the `bitnami/etcd` runs etcd as `ETCD_DAEMON_USER` which default value is `etcd`.

**Comment by sofire** [comment]
cd apisix-docker/example/
chown -R 1000:1000 etcd_data/
