### ISSUE TITLE
| nginx: [warn] could not build optimal variables_hash

### ISSUE THREAD

**Issue by fastopencn** [apache/apisix-docker#193]
➜  workspace git clone https://github.com/apache/apisix-docker.git
Cloning into 'apisix-docker'...
remote: Enumerating objects: 739, done.
remote: Counting objects: 100% (273/273), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 739 (delta 127), reused 230 (delta 99), pack-reused 466
Receiving objects: 100% (739/739), 152.00 KiB | 251.00 KiB/s, done.
Resolving deltas: 100% (339/339), done.
➜  workspace cd apisix-docker/example
➜  example git:(master) docker compose up       
[+] Running 6/6
 ⠿ Network example_apisix                Created                                                                                                                        3.8s
 ⠿ Container example_etcd_1              Started                                                                                                                        8.0s
 ⠿ Container example_web2_1              Started                                                                                                                        4.8s
 ⠿ Container example_web1_1              Started                                                                                                                        9.1s
 ⠿ Container example_apisix-dashboard_1  Started                                                                                                                        6.7s
 ⠿ Container example_apisix_1            Started                                                                                                                       12.4s
Attaching to apisix-dashboard_1, apisix_1, etcd_1, web1_1, web2_1
apisix_1            | 
apisix_1            | WARNING: using fixed Admin API token has security risk.
apisix_1            | Please modify "admin_key" in conf/config.yaml .
apisix_1            | 
apisix_1            | 
apisix_1            | /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
apisix_1            | nginx: [warn] could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by Yiyiyimu** [comment]
Hi @fastopencn it got fixed in https://github.com/apache/apisix/pull/4344
Welcome using the latest docker image (2.7) which includes this patch

**Comment by fastopencn** [comment]
![image](https://user-images.githubusercontent.com/68014289/124409807-a68e6d80-dd7b-11eb-96d5-521bd7aabe17.png)
1、apache/apisix-dashboard:2.7
2、apache/apisix:2.7-alpine
3、bitnami/etcd:3.4.15
4、nginx:1.19.0-alpine

**Comment by fastopencn** [comment]
1、apache/apisix-dashboard:2.7
2、apache/apisix:2.7-alpine
3、bitnami/etcd:3.5.0
4、nginx:nginx:1.19.0-alpine

It's stuck here....

➜  example git:(master) ✗ docker compose up
[+] Running 9/9
 ⠿ etcd Pulled                                                                                                                                         7.8s
   ⠿ fd7a9faefc3c Pull complete                                                                                                                        4.2s
   ⠿ a2be5217dc2d Pull complete                                                                                                                        4.3s
   ⠿ c788f2c46b1b Pull complete                                                                                                                        4.7s
   ⠿ 8ea56786157f Pull complete                                                                                                                        4.8s
   ⠿ da37b9f1dc32 Pull complete                                                                                                                        5.7s
   ⠿ c646c2e2417c Pull complete                                                                                                                        5.8s
   ⠿ 90dd12355549 Pull complete                                                                                                                        5.9s
   ⠿ 933e41e9f3eb Pull complete                                                                                                                        6.0s
[+] Running 5/5
 ⠿ Container example_web1_1              Started                                                                                                       5.1s
 ⠿ Container example_etcd_1              Started                                                                                                       7.1s
 ⠿ Container example_apisix-dashboard_1  Started                                                                                                      10.1s
 ⠿ Container example_web2_1              Started                                                                                                       8.8s
 ⠿ Container example_apisix_1            Started                                                                                                      12.2s
Attaching to apisix-dashboard_1, apisix_1, etcd_1, web1_1, web2_1
apisix_1            | 
apisix_1            | WARNING: using fixed Admin API token has security risk.
apisix_1            | Please modify "admin_key" in conf/config.yaml .
apisix_1            | 
apisix_1            | 
apisix_1            | /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd

**Comment by tokers** [comment]
This is not a fatal error but if you really concern about it, just configuring it by yourself. The above link sent by @Yiyiyimu just tell you we add some capabilities to let APISIX customize this setting, not saying upgrading the image version can solve this problem.
