### ISSUE TITLE
Request Error Code: 2000001 The manager-api and apache apisix are mismatched.

### ISSUE THREAD

**Issue by frui85** [apache/apisix-docker#195]
![image](https://user-images.githubusercontent.com/10277372/124845897-45100e00-dfca-11eb-9b89-05ee992ce636.png)

**Comment by luckydog85** [comment]
自带同版本怎么不匹配

**Comment by tao12345666333** [comment]
There is a version difference between apisix-dashboard and apisix now.
For example, apisix v2.7 and apisix-dashboard v2.7 can work together.
