### ISSUE TITLE
feat request: build dashboard docker image on travis ci ARM machine

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-docker#200]
We tried to build dashboard docker image for ARM in #197 but failed. Since I could build dashboard docker image on m1 so there's nothing to do with the building process itself.

And since it stuck at `yarn build`, a large chance is free Github Actions machine is lack of memory since we also deploy `QEMU` to simulate arm environment, as [ref](https://stackoverflow.com/questions/59868448/rpc-error-code-unknown-desc-failed-to-build-llb) suggests. So one possible way I think is to use travis CI to build the image, since travis supports arm machine by itself so we could remove the rely on QEMU.

There are two steps to finish this feature:
- [ ] build dashboard docker image on ARM in travis CI
- [ ] support the same trigger to push it to dockerhub like [what we do in Github Actions](https://github.com/apache/apisix-docker/blob/master/.github/workflows/dashboard_push_docker_hub.yaml#L4)

_Originally posted by @Yiyiyimu in https://github.com/apache/apisix-docker/issues/197#issuecomment-887885943_

---

ps: just found Apache Arrow is using this method: https://github.com/apache/arrow/pull/7085

**Comment by soulbird** [comment]
apisix related projects no longer use travis ci.
