### ISSUE TITLE
k8s 环境apisix集成prometheus，apisix和prometheus的配置如何设置？

### ISSUE THREAD

**Issue by wjmmjr** [apache/apisix-docker#203]
按照虚拟机的配置方式，apisix和prometheus集成失败

**Comment by Yiyiyimu** [comment]
Hi @wjmmjr could you provide some detail steps about how you deploy apisix and prometheus

**Comment by spacewander** [comment]
Duplicate of https://github.com/apache/apisix/issues/4744?
