### ISSUE TITLE
request help: can the official docker image be built with the dependencies required by buildin plugins

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix-docker#208]
### Issue description

When I enable the client-control plugin, I encounter an error: "need to build APIs IX openrest to support client restriction"

Therefore, can the official docker image be built with the dependencies required by the plug-in?

### Environment

- apisix version (cmd: `apisix version`): 2.8-docker

**Comment by nic-chen** [comment]
@gxthrj  please have a look.

**Comment by soulbird** [comment]
The apisix docker image already uses apisix-base as runtime, this issue seems to be outdated
