### ISSUE TITLE
没有办法在dashboard设置batch-requests

### ISSUE THREAD

**Issue by feipengheart** [apache/apisix-docker#211]
![image](https://user-images.githubusercontent.com/66514726/131618563-29f72981-0028-4a01-a236-7add7c46d560.png)
没有办法对单一的路由设置batch-requests，

curl http://127.0.0.1:9080/apisix/admin/plugin_metadata/batch-requests -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
"max_body_size": 4194304
}'

这个api设置只会对/apisix/admin/plugin_metadata/batch-requests路径剩下，我自己设置的路由并有效果

**Comment by tokers** [comment]
> ![image](https://user-images.githubusercontent.com/66514726/131618563-29f72981-0028-4a01-a236-7add7c46d560.png)
> 没有办法对单一的路由设置batch-requests，
> 
> curl http://127.0.0.1:9080/apisix/admin/plugin_metadata/batch-requests -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
> "max_body_size": 4194304
> }'
> 
> 这个api设置只会对/apisix/admin/plugin_metadata/batch-requests路径剩下，我自己设置的路由并有效果

Yep, the configuration about `max_body_size` is inside the plugin metadata. So you don't have to configure this plugin in any routes.
