### ISSUE TITLE
docker制作镜像文件问题standard_init_linux.go:208: exec user process caused "no such file or direct

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix-docker#217]
docker-daashboard制作镜像后启动容器就报错

报错：standard_init_linux.go:208: exec user process caused "no such file or direct

网上都说：文件格式问题，但是咱没有这个问题是unix格式。

经过排查问题是基础镜像的问题，dockerfile里的from alpine:latest，alpine:latest就有这个问题，改成centos后就没问题了

**Comment by 18300618319** [comment]
这是基础镜像的问题有人能解决吗

**Comment by tokers** [comment]
@18300618319 How did you run the container?

**Comment by 18300618319** [comment]
有人知道这是什么问题吗

**Comment by starsz** [comment]
> dockerfile里的from alpine:latest，alpine:latest就有这个问题，改成centos后就没问题了

Do you mean to change the dockerfile ?
