### ISSUE TITLE
2379: bind: address already in use

### ISSUE THREAD

**Issue by vcqr** [apache/apisix-docker#227]
执行：docker-compose -p docker-apisix up -d
[+] Running 3/4
 ⠿ Container docker-apisix_web2_1              Running                                                                                                                                                                                   0.0s
 ⠿ Container docker-apisix_web1_1              Running                                                                                                                                                                                   0.0s
 ⠿ Container docker-apisix_apisix-dashboard_1  Started                                                                                                                                                                                   0.1s
 ⠙ Container docker-apisix_etcd_1              Starting                                                                                                                                                                                  0.1s
Error response from daemon: driver failed programming external connectivity on endpoint docker-apisix_etcd_1 (36f4b64605c13698e18c405697d774f27ed56aed48beb01e71b70ab2d3487e0d): Error starting userland proxy: listen tcp4 0.0.0.0:2379: bind: address already in use

执行：lsof -i:2379
没有看到端口有占用
系统：macOS 11.6 (20G165)

**Comment by vcqr** [comment]
没有人帮忙看看吗？

**Comment by tokers** [comment]
Make sure the docker network `apisix` is removed before you run this, since legacy ETCD might still there so when you launch another ETCD, it will complain about the address is already in use.

**Comment by vcqr** [comment]
我把自己安装的etcd都已停掉了， lsof查看都是没有相应的进程

**Comment by tokers** [comment]
> 我把自己安装的etcd都已停掉了， lsof查看都是没有相应的进程

Not only programs in your hosts, but also others in containers.

**Comment by biubiue** [comment]
same +1

**Comment by membphis** [comment]
@biubiue do you still have this issue?

**Comment by biubiue** [comment]
> @biubiue do you still have this issue?

I has resolved this problem , by stop my local k8s

**Comment by membphis** [comment]
I think we can close this issue. @vcqr if you still have question, pls feel free to reopen this issue ^_^

**Comment by vcqr** [comment]
> > @biubiue do you still have this issue?
> 
> I has resolved this problem , by stop my local k8s

这样是正解
