### ISSUE TITLE
occur docker build error via apisix-docker/all-in-one/apisix

### ISSUE THREAD

**Issue by farsking** [apache/apisix-docker#248]
(38/40) Installing libldapcpp (2.4.50-r2)
(39/40) Installing openldap-dev (2.4.50-r2)
(40/40) Installing .builddeps (20211124.062630)
Executing busybox-1.31.1-r20.trigger
OK: 366 MiB in 127 packages
+ luarocks install https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec '--tree=/usr/local/apisix/deps'

Error: Could not load rockspec file /tmp/luarocks_luarocks-rockspec-apisix-master-0-AfU5Ji/apisix-master-0.rockspec (Error loading **file: [string "/tmp/luarocks_luarocks-rockspec-apisix-master-0-AfU5Ji/apisix-m..."]:7: unexpected symbol near '<')**
The command '/bin/sh -c set -x     && (test "${ENABLE_PROXY}" != "true" || /bin/sed -i 's,http://dl-cdn.alpinelinux.org,https://mirrors.aliyun.com,g' /etc/apk/repositories)     && apk add --no-cache --virtual .builddeps     automake     autoconf     libtool     pkgconfig     cmake     git     pcre     pcre-dev     openldap-dev     && luarocks install https://github.com/apache/apisix/blob/master/rockspec/apisix-${APISIX_VERSION}-0.rockspec --tree=/usr/local/apisix/deps     && cp -v /usr/local/apisix/deps/lib/luarocks/rocks-5.1/apisix/${APISIX_VERSION}-0/bin/apisix /usr/bin/     && (if [ "$APISIX_VERSION" = "master" ] || [ "$APISIX_VERSION" \> "2.2" ]; then echo 'use shell ';else bin='#! /usr/local/openresty/luajit/bin/luajit\npackage.path = "/usr/local/apisix/?.lua;" .. package.path'; sed -i "1s@.*@$bin@" /usr/bin/apisix ; fi;)     && mv /usr/local/apisix/deps/share/lua/5.1/apisix /usr/local/apisix     && apk del .builddeps build-base make unzip' returned a non-zero code: 1
----------------------------------------------------------------------------------------
I try to build images via docker command "docker build -t apache/apisix ." and failed , any helps for me pls

**Comment by spacewander** [comment]
We need to change https://github.com/apache/apisix-docker/blob/829d45559c303bea7edde5bebe9fcf4938071601/all-in-one/apisix/Dockerfile#L27 to https://github.com/apache/apisix-docker/blob/829d45559c303bea7edde5bebe9fcf4938071601/alpine/Dockerfile#L24

PR is welcome!

**Comment by mohitsaxenaknoldus** [comment]
@spacewander PR: https://github.com/apache/apisix-docker/pull/249
