### ISSUE TITLE
real-ip plugin can not work

### ISSUE THREAD

**Issue by zzyork** [apache/apisix-docker#253]
I deployed an apisix with docker-compose, but when using the real-ip plugin, I found that the plug-in always failed to take effect.!

This is real-ip plugin's json config: 
```json
  "plugins": {
    "real-ip": {
      "source": "X-Forwarded-For",
      "trusted_addresses": [
        "39.0.0.0/8",
        "10.10.0.0/16"
      ]
    }
  }
```
But when I visit, access.log still records the address of 10.10.xxx.xxx. This IP address is the IP of my upper layer nginx.
![image](https://user-images.githubusercontent.com/45233837/146162913-2815d1b8-ef08-4231-8a16-7ec0536f118a.png)
![image](https://user-images.githubusercontent.com/45233837/146163552-658d05fa-87c3-4dc1-8743-6dea686e18ac.png)

should be 117.x.x.x

**Comment by zzyork** [comment]
Did I configure it wrong?

**Comment by tokers** [comment]
> Did I configure it wrong?

What's the tag of￼ your apisix docker?

**Comment by zzyork** [comment]
it's 2.11.0-alpine
![image](https://user-images.githubusercontent.com/45233837/146294584-535bb876-34d9-4b85-8e6a-55c83a6e60fd.png)

**Comment by zzyork** [comment]
> > Did I configure it wrong?
> 
> What's the tag of￼ your apisix docker?



> > Did I configure it wrong?
> 
> What's the tag of￼ your apisix docker?

it's `2.11.0-alpine`
![image](https://user-images.githubusercontent.com/45233837/146295087-1abe03ae-708a-475f-a9b4-9007280b4bbd.png)

**Comment by zzyork** [comment]
> > Did I configure it wrong?
> 
> What's the tag of￼ your apisix docker?

it's `2.11.0-alpine`
https://github.com/apache/apisix-docker/issues/253#issuecomment-994724016

**Comment by membphis** [comment]
Can you provide a full test case? We need to confirm whether it is a bug.

**Comment by zzyork** [comment]
> Can you provide a full test case? We need to confirm whether it is a bug.

Thank you for your help, I found the reason, because I configured a wrong plug-in in config.yaml, which caused all the plug-ins to not work. Currently real-ip has been working normally.
