### ISSUE TITLE
bug: wrong APISIX ARM64 image

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix-docker#255]
Previously, we used `openresty/openresty` as the base image, which can support ARM64 architecture. And now we switch to `api7/apisix-base` as the base image, which does not support ARM64, and based on the original CI build infrastructure, we are still releasing ARM64-based APISIX images, so currently there is an ARM64 APISIX image using x86_64 `apisix-base` as the base, which does not work properly.

**Comment by spacewander** [comment]
Good catch! Is it urgent to fix?

**Comment by tokers** [comment]
@LYignore I have assigned this issue to you, thanks!

**Comment by juzhiyuan** [comment]
Hi @LYignore, may I know if you need any help?

**Comment by bzp2010** [comment]
@LYignore This issue is not the same as your question. This issue is about `apisix-base`.

**Comment by LYignore** [comment]
@bzp2010 Thank you very much, I made a mistake, I will learn how to fix this problem
