### ISSUE TITLE
The dev image is broken

### ISSUE THREAD

**Issue by haoxins** [apache/apisix-docker#272]
The latest dev image can't start correctly, [Docker hub link](https://hub.docker.com/layers/apache/apisix/dev/images/sha256-84b4561af462f48ebd0b04a60e8b9c5aa1aeffdd20a3b38bf81d0313dded1d8d)

```
DIGEST:sha256:84b4561af462f48ebd0b04a60e8b9c5aa1aeffdd20a3b38bf81d0313dded1d8d
```

the error messages are

```
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init

/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
2022/01/17 11:16:31 [emerg] 1#1: unknown directive "apisix_mirror_on_demand" in /usr/local/apisix/conf/nginx.conf:99
nginx: [emerg] unknown directive "apisix_mirror_on_demand" in /usr/local/apisix/conf/nginx.conf:99
```

But with image `2.11.0-alpine` no any issue found.

I deploy APISIX with the official Helm chart.

**Comment by leslie-tsang** [comment]
Hello there, a new version has been released, can you try the new version?

**Comment by haoxins** [comment]
https://hub.docker.com/layers/apache/apisix/dev/images/sha256-e04e8c3cce0344faba4dfc040c19e97750a7ac90a4a58f25a1a4355d4e753ede?context=explore fixed this issue, thanks~
