### ISSUE TITLE
request help: Invalid plugin data should have required property 'client_id' (openid-connect)

### ISSUE THREAD

**Issue by grainrain** [apache/apisix-docker#274]
Issue description
apisix installation by docker-compose https://github.com/apache/apisix-docker/tree/master/example
when enable openid-connect plugin , happer error
error image url : https://github.com/grainrain/issues/blob/main/Snipaste_2022-01-21_08-41-49.png
Invalid plugin data should have required property 'client_id'
above operation by apisix dashboard, I can not find any place can fill client_id for openid-connect plugin in portal
please help to fix
plus : I config in apisix dashbord portal ,   the error happen when I config in dashboard

Environment
apisix version (cmd: apisix version): 2.11.0
apisix-dashboard version, if have:2.10.1

**Comment by starsz** [comment]
Hello, @grainrain .
You should pass your config like this:
![image](https://user-images.githubusercontent.com/25628854/150453418-65011d8f-eec6-4963-8193-dea33bb8dab9.png)

And the openid-plugin config, you can refer: https://apisix.apache.org/docs/apisix/plugins/openid-connect

**Comment by grainrain** [comment]
> Hello, @grainrain . You should pass your config like this: ![image](https://user-images.githubusercontent.com/25628854/150453418-65011d8f-eec6-4963-8193-dea33bb8dab9.png)
> 
> And the openid-plugin config, you can refer: https://apisix.apache.org/docs/apisix/plugins/openid-connect

Thanks for  your reply 

https://github.com/grainrain/issues/blob/main/2022-01-21_09-41-42.png


please view the image url , I can not edit , Raw Data Editor disable
