### ISSUE TITLE
bug: apache/apisix:2.12.0-alpine image misses some packages

### ISSUE THREAD

**Issue by jiangy** [apache/apisix-docker#277]
There are maybe some problem for the building of apache/apisix:2.12.0-alpine.
It misses some packages such as openldap-dev which makes ldap-auth plugin load failed

**Comment by spacewander** [comment]
Can't reproduce on my side. Also the openldap-dev is listed in the Dockerfile: https://github.com/apache/apisix-docker/blob/ced794a6e94f905e0b9998f3b7554d22bed70a7d/alpine/Dockerfile#L43

**Comment by jiangy** [comment]
> Can't reproduce on my side. Also the openldap-dev is listed in the Dockerfile:
> 
> https://github.com/apache/apisix-docker/blob/ced794a6e94f905e0b9998f3b7554d22bed70a7d/alpine/Dockerfile#L43

reproduce：
`
➜  example git:(master) git remote -v
origin	https://github.com/apache/apisix-docker.git (fetch)
origin	https://github.com/apache/apisix-docker.git (push)
➜  example git:(master) vim docker-compose.yml
➜  example git:(master) ✗ git diff | cat
diff --git a/example/docker-compose.yml b/example/docker-compose.yml
index a182f39..0e972b8 100644
--- a/example/docker-compose.yml
+++ b/example/docker-compose.yml
@@ -29,7 +29,7 @@ services:
       apisix:

   apisix:
-    image: apache/apisix:2.11.0-alpine
+    image: apache/apisix:2.12.0-alpine
     restart: always
     volumes:
       - ./apisix_log:/usr/local/apisix/logs
➜  example git:(master) ✗ docker-compose -p docker-apisix up -d
Creating network "docker-apisix_apisix" with driver "bridge"
Creating volume "docker-apisix_etcd_data" with local driver
Creating docker-apisix_web1_1             ... done
Creating docker-apisix_web2_1             ... done
Creating docker-apisix_apisix-dashboard_1 ... done
Creating docker-apisix_prometheus_1       ... done
Creating docker-apisix_etcd_1             ... done
Creating docker-apisix_grafana_1          ... done
Creating docker-apisix_apisix_1           ... done
➜  example git:(master) ✗ grep 'error loading' -A 1 apisix_log/error.log
2022/01/29 06:29:24 [error] 46#46: *3 [lua] plugin.lua:109: load_plugin(): failed to load plugin [ldap-auth] err: error loading module 'lualdap' from file '/usr/local/apisix//deps/lib/lua/5.1/lualdap.so':
	Error loading shared library libldap-2.4.so.2: No such file or directory (needed by /usr/local/apisix//deps/lib/lua/5.1/lualdap.so), context: init_worker_by_lua*
--
2022/01/29 06:29:24 [error] 45#45: *2 [lua] plugin.lua:109: load_plugin(): failed to load plugin [ldap-auth] err: error loading module 'lualdap' from file '/usr/local/apisix//deps/lib/lua/5.1/lualdap.so':
	Error loading shared library libldap-2.4.so.2: No such file or directory (needed by /usr/local/apisix//deps/lib/lua/5.1/lualdap.so), context: init_worker_by_lua*
--
2022/01/29 06:29:24 [error] 47#47: *5 [lua] plugin.lua:109: load_plugin(): failed to load plugin [ldap-auth] err: error loading module 'lualdap' from file '/usr/local/apisix//deps/lib/lua/5.1/lualdap.so':
	Error loading shared library libldap-2.4.so.2: No such file or directory (needed by /usr/local/apisix//deps/lib/lua/5.1/lualdap.so), context: init_worker_by_lua*
--
2022/01/29 06:29:24 [error] 50#50: *4 [lua] plugin.lua:109: load_plugin(): failed to load plugin [ldap-auth] err: error loading module 'lualdap' from file '/usr/local/apisix//deps/lib/lua/5.1/lualdap.so':
	Error loading shared library libldap-2.4.so.2: No such file or directory (needed by /usr/local/apisix//deps/lib/lua/5.1/lualdap.so), context: init_worker_by_lua*
--
2022/01/29 06:29:24 [error] 44#44: *1 [lua] plugin.lua:109: load_plugin(): failed to load plugin [ldap-auth] err: error loading module 'lualdap' from file '/usr/local/apisix//deps/lib/lua/5.1/lualdap.so':
	Error loading shared library libldap-2.4.so.2: No such file or directory (needed by /usr/local/apisix//deps/lib/lua/5.1/lualdap.so), context: init_worker_by_lua*
➜  example git:(master) ✗ docker exec -it docker-apisix_apisix_1 bash
bash-5.1# apk list --installed | grep openldap-dev
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: No such file or directory
bash-5.1# ls /usr/lib/libldap-2.4.so.2
ls: /usr/lib/libldap-2.4.so.2: No such file or directory
`

**Comment by jiangy** [comment]
![image](https://user-images.githubusercontent.com/2594973/151650654-aa219756-cfea-447a-84ef-70316ae93254.png)

**Comment by spacewander** [comment]
Thanks for the report!
