### ISSUE TITLE
docs: need update README. 

### ISSUE THREAD

**Issue by mangoGoForward** [apache/apisix-docker#288]
As the [issue](https://github.com/apache/apisix/issues/6332) said, there should be `make build-dashboard-centos` or `make build-dashboard-alpine` instead of `make build-dashboard`.

And I noticed that the current context is `All in one Docker container for Apache apisix-dashboard`, but all-in-one would not build dashboard image.

**Expected behavior**
1. make a new section to describe build dashboard image.
2. use `make build-dashboard-centos` or `make build-dashboard-alpine` instead of `make build-dashboard`.

**Comment by tokers** [comment]
@mangoGoForward Welcome to submit a PR!
