### ISSUE TITLE
WARNING: Network apisix_apisix not found.

### ISSUE THREAD

**Issue by VineFiner** [apache/apisix-docker#290]
I use the demo and it fails when stopped.

```
docker-compose -v
docker-compose version 1.28.6, build 5db8d86f
```

Warning

```
docker-compose down
Removing network apisix_apisix
WARNING: Network apisix_apisix not found.
```

**Comment by tokers** [comment]
How did you start these containers? Could you provide the reproduce steps.

**Comment by leslie-tsang** [comment]
> docker-compose down
Removing network apisix_apisix
WARNING: Network apisix_apisix not found.

It's acceptable if the network is not found when during `docker-compose down`

**Comment by VineFiner** [comment]
> How did you start these containers? Could you provide the reproduce steps.

https://apisix.apache.org/docs/apisix/getting-started/

```
# Download the Docker image of Apache APISIX
git clone https://github.com/apache/apisix-docker.git
# Switch the current directory to the apisix-docker/example path
cd apisix-docker/example
# Run the docker-compose command to install Apache APISIX
docker-compose -p docker-apisix up -d
```

**Comment by VineFiner** [comment]
docker-compose -p docker-apisix down
