### ISSUE TITLE
add travis CI for docker

### ISSUE THREAD

**Issue by moonming** [apache/apisix-docker#3]

**Comment by moonming** [comment]
here is a example:https://github.com/c9s/r3/blob/2.0/.travis.yml

**Comment by hiproz** [comment]
i think this is a necessary and interesting work

**Comment by moonming** [comment]
@hiproz great, welcome PR:)

**Comment by Aju100** [comment]
Hey, @moonming I think this is inactive for a long time. Can I work on this issue?

**Comment by Yiyiyimu** [comment]
> Hey, @moonming I think this is inactive for a long time. Can I work on this issue?

Hi @aju We've already got Github Actions to do most of the jobs. Maybe you could work on building images for ARM64 since that's the unique part of Travis CI and I think we need it

**Comment by Aju100** [comment]
HI @Yiyiyimu,

Before going to solve this issue, may I know should I go with Travis CI to build an image for ARM64 or with Github Actions. I am confused about your tasks. 

Thanks

**Comment by Yiyiyimu** [comment]
Hi @Aju100 Github Actions only support x86 system so Travis CI is the only choice for us I think
