### ISSUE TITLE
Redesign the document architecture of apisix-docker

### ISSUE THREAD

**Issue by Chever-John** [apache/apisix-docker#300]
# Issue description

## Current situation

Now we have many following commands:

```sh
make build-on-centos           : Build apache/apisix:xx-centos image
make build-on-alpine           : Build apache/apisix:xx-alpine image
make build-on-alpine-dev       : Build apache/apisix:xx-alpine-dev image
make build-on-alpine-local     : Build apache/apisix:xx-alpine-local image
make push-on-centos            : Push apache/apisix:xx-centos image
make push-on-alpine            : Push apache/apisix:xx-alpine image
make push-on-alpine            : Push apache/apisix:dev image
make build-on-alpine-cn        : Build apache/apisix:xx-alpine image (for chinese)
make build-all-in-one          : Build All in one Docker container for Apache APISIX
make build-dashboard-all-in-one  : Build All in one Docker container for Apache APISIX-dashboard
make save-centos-tar           : tar apache/apisix:xx-centos image
make save-alpine-tar           : tar apache/apisix:xx-alpine image
make build-dashboard-centos    : Build apache/dashboard:tag image on centos
make build-dashboard-alpine    : Build apache/dashboard:tag image on alpine
make push-multiarch-dashbaord  : Build and push multiarch apache/dashboard:tag image
make save-dashboard-centos-tar  : tar apache/apisix-dashboard:tag image
make save-dashboard-alpine-tar  : tar apache/apisix-dashboard:tag image
make help                      : Show Makefile rules
```

Although we have many useful commands, the fact is that our README.md file does not cover them all.

A good documentation organization can facilitate developers to add some useful content.

I want to finish this task to redesign the structure of the README.md

## Proposal

My tentative plan for the file structure is as follows, I would be grateful for some advice.

- build
  - apisix
    - centos
    - alpine
      - dev
      - local
      - cn
  - dashboard
    - centos
    - Alpine
  - All-in-one
    - apisix
    - dashboard
- push
  - centos
  - alpine
    - cn
  - multiarch-dashboard
- tar
  - apisix
    - centos
    - alpine
  - dashboard
    - centos
    - Alpine

Organize the way docker is deployed in a way. This will help apisix developers in their daily development.

**Comment by spacewander** [comment]
I would suggest organizing the doc according to the purpose: centos/alpine/dev/arm64/all-in-one/dashboard, not the build/push operation.

CC @juzhiyuan

**Comment by Chever-John** [comment]
Hi, I have changed the structure. Please review it. @spacewander 

- centos
  - X86-64
    - normal use:
      make build-on-centos
      make push-on-centos
      make save-centos-tar
    - dev:  
      make build-on-alpine-dev
    - alpine: 
      make build-on-alpine
      make build-on-alpine-cn
      make build-on-alpine-local
      make push-on-alpine
      make save-alpine-tar
    - All-in-one:
      make build-all-in-one
      make build-dashboard-all-in-one
      make build-dashboard-centos
      make build-dashboard-alpine
      make push-multiarch-dashboard
      make save-dashboard-centos-tar
      make save-dashboard-alpine-tar
- make help

**Comment by tokers** [comment]
Besides the structures, what contents will be written there? Only the directive? I hope some tips should be given such as the limitations on this arch.

**Comment by Chever-John** [comment]
@tokers 

There will, of course, be descriptive information about each command. As well as possible caveats, such as hints on system architecture requirements.

The expected result to be achieved could look like this: https://en.cppreference.com/w/cpp/utility/optional#:~:text=T-,Member%20functions,-(constructor)

**Comment by Chever-John** [comment]
If there are no additional things to note, I will write the first version of the document out tonight first.

**Comment by spacewander** [comment]
> Hi, I have changed the structure. Please review it. @spacewander
> 
>     * centos
>       
>       * X86-64
>         
>         * normal use:
>           make build-on-centos
>           make push-on-centos
>           make save-centos-tar
>         * dev:
>           make build-on-alpine-dev
>         * alpine:
>           make build-on-alpine
>           make build-on-alpine-cn
>           make build-on-alpine-local
>           make push-on-alpine
>           make save-alpine-tar
>         * All-in-one:
>           make build-all-in-one
>           make build-dashboard-all-in-one
>           make build-dashboard-centos
>           make build-dashboard-alpine
>           make push-multiarch-dashboard
>           make save-dashboard-centos-tar
>           make save-dashboard-alpine-tar
> 
>     * make help

It's confusing. Why centos is the same level of `make help`? And there is no need to write a doc about `make help` or `make save-` or `make upload-` which are unnecessary for the users.

**Comment by juzhiyuan** [comment]
also cc @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
One thing to note is that we should ensure parity between the README and the APISIX Docker docs on the website. README can be made as simple as possible in my opinion since more information can be presented in a better format in the website.

**Comment by Chever-John** [comment]
> One thing to note is that we should ensure parity between the README and the APISIX Docker docs on the website. README can be made as simple as possible in my opinion since more information can be presented in a better format in the website.

Yes, but this repository is developer-oriented and not user-oriented. What I am trying to do is improve the completeness of the documentation and the extensibility.

**Comment by VioletZhouECE** [comment]
I'd like to work on this issue. Please assign this to me.

**Comment by Chever-John** [comment]
@VioletZhouECE 
Hi, can you say something about this issue? I'd be happy if you could suggest ways to improve this proposal～

**Comment by navendu-pottekkat** [comment]
We could also focus on how to use the Docker image/Docker compose file instead of focusing on building the Docker image. Users would likely only care about the Docker image and the files and not about how to build their own images.

**Comment by Chever-John** [comment]
@navendu-pottekkat 
Yes, we need to think about our users. And we must insist that this document should be intended for users.
Please continue your work with this goal~ @VioletZhouECE

**Comment by VioletZhouECE** [comment]
Thanks for the comments! Here is a draft README that mostly follows the file structure Chever proposed with some small modifications - the main change I made is separating APISIX and APISIX dashboard into their own sections: https://github.com/VioletZhouECE/apisix-docker#all-commands
Let me know if the structure makes sense.

I'm not sure about the supported arch for each command so I didn't add that to README. The description for each command probably still needs some work (I'm not very sure what each of them does and my understanding could be off). 

What content should the description contain? Personally I think the command description should be very consice (like 1-2 sentences) since many of them are very self-explainatory.

**Comment by Chever-John** [comment]
@VioletZhouECE 
Hi, we do not need commands like `make tar` & `make save`. 
We need the commands contained in this [link](https://hub.docker.com/r/apache/apisix)

**Comment by spacewander** [comment]
> Thanks for the comments! Here is a draft README that mostly follows the file structure Chever proposed with some small modifications - the main change I made is separating APISIX and APISIX dashboard into their own sections: https://github.com/VioletZhouECE/apisix-docker#all-commands Let me know if the structure makes sense.
> 
> I'm not sure about the supported arch for each command so I didn't add that to README. The description for each command probably still needs some work (I'm not very sure what each of them does and my understanding could be off).
> 
> What content should the description contain? Personally I think the command description should be very consice (like 1-2 sentences) since many of them are very self-explainatory.

A command list is not what we want for the new doc.
See:
https://github.com/apache/apisix-docker/issues/303
https://github.com/apache/apisix-docker/issues/300#issuecomment-1110577375

@navendu-pottekkat 
Could you provide some guide to the contributor?

**Comment by navendu-pottekkat** [comment]
@VioletZhouECE https://github.com/apache/apisix-docker/issues/300#issuecomment-1110577375 pretty much sums up the change needed in the document.

**Comment by navendu-pottekkat** [comment]
There are already docker-compose files and docker images. We want to help the user use those and get APISIX running. We do not want to show them how to build the docker image (because we have already built them and pushed to docker hub). The building part can be added to the end of the doc for developers who require some customization.

**Comment by VioletZhouECE** [comment]
Hmm I'm still a little confused... 
I think the existing doc already explains how to get APISIX running:
```
cd example
docker-compose -p docker-apisix up -d 
```
and 
```
make build-all-in-one
# launch APISIX container
docker run -d \
-p 9080:9080 -p 9091:9091 -p 2379:2379 \
-v `pwd`/all-in-one/apisix/config.yaml:/usr/local/apisix/conf/config.yaml \
apache/apisix:whole
```

Can you give an example of what you meant by "helping the users use those commands"? What else do you think we need to document for `make build-all-in-one`, for example? Maybe different configs/flags they can use for docker run? Or how to do simple testing with the running containers to make sure that they work?

**Comment by navendu-pottekkat** [comment]
First would be how to use the Docker compose files to start APISIX, what are the configurations in the file etc.

Second would be how to use these Docker images https://hub.docker.com/search?q=apache%2Fapisix

Third would be how they can modify and make custom Docker images of APISIX.

**Comment by VioletZhouECE** [comment]
Gotcha! 
Yeah I think we need to document how to use the Docker compose files to start APISIX. 

I started some documentation (still WIP)
In **Run with Docker-compose**, I documented how to use the existing docker compose file, components/services in the docker compose file, and how the configs can be modified (maybe we can add more documentations for other common non-trivial modifications to the docker compose file, but I think most of the configs are in configs.yaml). 

In **Customize APISIX images**, I tried documenting how to customize apisix images, but I'm not very sure about the exact steps users need to take to build their own images. Are they supposed to modify the images provided in the repo? Are the images linked to images in the docker hub? Is `alpine/Dockerfile` the same as `apache/apisix:2.13.1-alpine`? 

### Run with Docker-compose
`/example` contains an example docker-compose file and config files that show how to start apisix and apisix dashboard using docker compose.
1. Start apisix and apisix dashboard
    ```
    cd example
    docker-compose -p docker-apisix up -d
    ```
 
2. Check if APISIX is running properly by running this command and checking the response.
    ```
    curl "http://127.0.0.1:9080/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
    ```
     The response indicates that apisix is running successfully:
    ```
    {
      "count":0,
      "action":"get",
      "node":{
        "key":"/apisix/services",
        "nodes":[],
        "dir":true
      }
    }
    ```
 
The example docker compose file defines several services: `apisix-dashboard, apisix, etcd, web1, web2, prometheus, and grafana`:
`apisix-dashboard, apisix, etcd` are the essential services required for starting apisix-dashboard, apisix, etcd.
`web1, web2` are services built on top of ningix images used for testing purposes.
`prometheus, grafana` are services used for exposing metrics of the running services.
 It also creates a bridge network `apisix` which connects all services and a `etcd_data` volume used by the `etcd` service. 

All the services are configured by mounting external configuration files onto the containers: `./dashboard_conf/conf.yaml` defines the configs for `apisix-dashboard`; `./apisix_conf/conf.yaml` defines the configs for apisix. Similarly, configs for etcd, prometheus, and grafana are located in the corresponding conf.yaml files. If you want to use a config file from a different path, you need to modify the local config file path in the `volumes` entry under the corresponding service.

### Customize APISIX images
We provide the following images:

- `/alpine/Dockerfile` builds apisix on alpine.

- `/centos/Dockerfile`builds apisix on centos.

- `/dashboard` contains two docker files - `Dockerfile.alpine` and `Dockerfile.centos`, which build apisix dashboard on alpine and centos respectively.

- `/all-in-one` enables you to quickly start apisix on alpine by following [these steps](https://github.com/apache/apisix-docker#quick-test-with-all-dependencies-in-one-docker-container).

We also provide some useful commands which build, push, and tar your updated images.
As an example, these are the commands for apisix-centos images:

-   ```make build-on-centos``` : Build apache/apisix:xx-centos image. 

-   ```make push-on-centos```: Build and push apache/apisix:xx-centos image.

-  ```make save-centos-tar```:  Save apache/apisix:xx-centos image to a tar archive located at ```./package``` . 

Similar commands exist for apisix-alpine images and apisix dashboard. See [the makefile](https://github.com/apache/apisix-docker/blob/master/Makefile) for a full list of commands.

**Comment by VioletZhouECE** [comment]
I also have some questions: 
1. Is `/alpine/Dockerfile` in the repo the same as `apache/apisix:2.13.1-alpine`? If not, what are the differences and which one should the user use?
2. What is the purpose of having `web1` `web2` services in `/example/docker-compose.yaml`? Seems like APISIX can be started without them.

**Comment by Chever-John** [comment]
@VioletZhouECE 
1. Maybe you're talking about `apisix-docker/all-in-one/apisix/Dockerfile` and `apisix-docker/alpine/Dockerfile`. The former packs an extra etcd, which makes it possible to fully boot APISIX after installation, while the latter just packs an APISIX image.

**Comment by VioletZhouECE** [comment]
I just opened a draft PR:
https://github.com/apache/apisix-docker/pull/305

**Comment by VioletZhouECE** [comment]
It seems like apisix and apisix dashboard are in two different places: https://hub.docker.com/r/apache/apisix, https://hub.docker.com/r/apache/apisix-dashboard, but they share the same README. Is it possible to have separate README for apisix and apisix dashboard? It is kinda difficult to find docs for apisix dashboard if we mix it with the huge amount of docs for apisix and put the docs for apisix first.

**Comment by VioletZhouECE** [comment]
Hi guys! I have some thoughts:
1. I think it's better to replace the `build` makefile commands with the actual docker build command for 2 reasons:
    1. From my understanding, most users will pull the docker hub image and read the documentation from the docker hub. So to use the makefile commands, they have to do the extra work of cloning the apisix-docker github repo and get used to a different flow. Most users are used to the flow of `docker pull`, `docker build`, `docker run`, `docker pull` (to get updeats), but not the flow of `git clone`, `make <command>`, `git pull`(to fetch updates).
    2. The actual build command is not much longer than the make command, so I don't think there are a lot of benefits in having a shortcut.
    For example, instead of: 
    ```
    # Assign Apache release version to variable `APISIX_VERSION`, for example: 2.9.
    # The latest release version can be find at `https://github.com/apache/apisix/releases`
    export APISIX_VERSION=2.9
    
    # build alpine based image
    make build-on-alpine
    
    # build centos based image
    make build-on-centos
    ```
    We can have:
    ```
    # Assign Apache release version to variable `APISIX_VERSION`, for example: 2.9.
    # The latest release version can be find at `https://github.com/apache/apisix/releases`
    export APISIX_VERSION=2.9
    
    # build alpine based image
    docker build -t $(ENV_APISIX_IMAGE_TAG_NAME)-alpine
    
    # build centos based image
    docker build -t $(ENV_APISIX_IMAGE_TAG_NAME)-centos
    ```
For developers, the make commands are easier because the developers work with the apisix-docker repo anyway, but this might not be the case for the users who do not work with the apisix-docker repo.

2. As we have APISIX and APISIX dashboard in two different places on the docker hub, I think it'd be a good idea to have separate docs for APISIX and APISIX dashboard. If we use the same documentation for both APISIX and APISIX dashboard, the docs for APISIX dashboard will be buried in the docs for APISIX, and the users will probably be confused about things like "why are they talking about APISIX dashboard in the docs for APISIX?"

I understand that we can't use APISIX dashboard without APISIX, but I think simply stating that "Before starting APISIX dashboard, please refer to this guide to start APISIX" is better than mixing the two docs together.

Is it possible to have separate docs for APISIX and APISIX dashboard?

**Comment by tokers** [comment]
> As we have APISIX and APISIX dashboard in two different places on the docker hub, I think it'd be a good idea to have separate docs for APISIX and APISIX dashboard. If we use the same documentation for both APISIX and APISIX dashboard, the docs for APISIX dashboard will be buried in the docs for APISIX, and the users will probably be confused about things like "why are they talking about APISIX dashboard in the docs for APISIX?"
> 
> I understand that we can't use APISIX dashboard without APISIX, but I think simply stating that "Before starting APISIX dashboard, please refer to this guide to start APISIX" is better than mixing the two docs together.
> 
> Is it possible to have separate docs for APISIX and APISIX dashboard?

Agree with you. Let's write a prerequisites section.

**Comment by tokers** [comment]
> 

I don't think so, and you can also check out the `.github/workflows` to verify it.

**Comment by spacewander** [comment]
> Is the `all-in-one` image on the docker hub? Looks like https://hub.docker.com/r/apache/apisix-all-in-one is not a valid link. Is the `alpine-local` image on the docker hub?

Only `alpine` & `centos` are the official release. Other images are considered as example or just for test.

**Comment by spacewander** [comment]
> As we have APISIX and APISIX dashboard in two different places on the docker hub, I think it'd be a good idea to have separate docs for APISIX and APISIX dashboard. If we use the same documentation for both APISIX and APISIX dashboard, the docs for APISIX dashboard will be buried in the docs for APISIX, and the users will probably be confused about things like "why are they talking about APISIX dashboard in the docs for APISIX?"
> 
> I understand that we can't use APISIX dashboard without APISIX, but I think simply stating that "Before starting APISIX dashboard, please refer to this guide to start APISIX" is better than mixing the two docs together.
> 
> Is it possible to have separate docs for APISIX and APISIX dashboard?

@juzhiyuan @navendu-pottekkat 
Please take charge of it, thanks!

**Comment by navendu-pottekkat** [comment]
> As we have APISIX and APISIX dashboard in two different places on the docker hub, I think it'd be a good idea to have separate docs for APISIX and APISIX dashboard. If we use the same documentation for both APISIX and APISIX dashboard, the docs for APISIX dashboard will be buried in the docs for APISIX, and the users will probably be confused about things like "why are they talking about APISIX dashboard in the docs for APISIX?"
> 
> I understand that we can't use APISIX dashboard without APISIX, but I think simply stating that "Before starting APISIX dashboard, please refer to this guide to start APISIX" is better than mixing the two docs together.
> 
> Is it possible to have separate docs for APISIX and APISIX dashboard?

Makes sense to have separate docs for both in Docker Hub. As you mentioned pointing to APISIX docs in the dashboard docs saying that you have to get APISIX running first is also a good idea.

**Comment by VioletZhouECE** [comment]
Okay I made some changes to the doc (see this draft PR).

Inspired by other docker hub docs (i.e.[httpd](https://hub.docker.com/_/httpd), thanks @Chever-John for sending the reference docs), I restructured the doc. Now it contains 5 sections:

- What is APISIX
- Image variants
- How to run APISIX
- How to build this Image
- Notes

I also removed everything related to the dashboard as we now decided to put it in a separate doc.

**Comment by navendu-pottekkat** [comment]
@VioletZhouECE Is the PR ready for review?

**Comment by VioletZhouECE** [comment]
It's not very polished, but some feedbacks on the general structure(i.e. which part is redundant/missing/needs more details) would be very helpful.

**Comment by Chever-John** [comment]
This issue is solved by @VioletZhouECE 
If you have another problem, feel free to reopen it again~
