### ISSUE TITLE
help request: apisix docker instance recommend resource value

### ISSUE THREAD

**Issue by stubbornTanzhe** [apache/apisix-docker#308]
### Description

is there any recommend resource value for operator to implement apisix instance in k8s?
better resource value per release version

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`):3.10.0-1160.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.4
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
cc @tao12345666333

**Comment by tokers** [comment]
By saying "resource value", do you mean the CPU and memory request and limit?

**Comment by stubbornTanzhe** [comment]
> 

yes, cpu and memory resource

**Comment by stubbornTanzhe** [comment]
> In fact the best configuration depends on your actual stress test results in your own environment.

maybe some best suggestion,such as "better performance on multi-core" or "multi-core unnecessary" or "100Mi at least"?

**Comment by tao12345666333** [comment]
For performance, it's not just about CPU and memory, there are many things to consider, such as how to handle connections, whether to compress, timeout, keep-alive etc.

If you focus the question on the CPU, the number of cores is directly related to the configuration of APISIX's `worker_processes`. But you also need to pay attention to the configuration of `worker_cpu_affinity`.
