### ISSUE TITLE
some question in build apisix-docker all in one

### ISSUE THREAD

**Issue by liujun69** [apache/apisix-docker#315]
it always failed in stage 
`luarocks install https://github.com/apache/apisix/row/master/rockspec/apisix-${APISIX_VERSION}-0.rockspec --tree=/usr/local/apisix/deps PCRE_DIR=/usr/local/openresty/pcre`
and prompt connect refused
Whether I turn on the network proxy or not

**Comment by tokers** [comment]
The reason is clear, the `luaxxhash` repo cannot be cloned, might be due to the network problem.
