### ISSUE TITLE
The maximum number of active connections for UID 0 has been reached

### ISSUE THREAD

**Issue by RexHuang** [apache/apisix-docker#327]
### Current Behavior

$ docker-compose up

### Expected Behavior

apisix should up and running

### Error Logs

$ docker-compose up
Creating network "example_apisix" with driver "bridge"
Creating example_apisix-dashboard_1 ... error
Creating example_etcd_1             ...

ERROR: for example_apisix-dashboard_1  Cannot start service apisix-dashboard: oci runtime error: The maximum number of active connections for UID 0 has been reaCreating example_etcd_1             ... error

ERROR: for example_etcd_1  Cannot start service etcd: oci runtime error: The maximum number of active connections for UID 0 has been reached

ERROR: for apisix-dashboard  Cannot start service apisix-dashboard: oci runtime error: The maximum number of active connections for UID 0 has been reached

ERROR: for etcd  Cannot start service etcd: oci runtime error: The maximum number of active connections for UID 0 has been reached
ERROR: Encountered errors while bringing up the project.

### Steps to Reproduce

version: "3"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.10.1-alpine
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      apisix:

  apisix:
    image: apache/apisix:2.13.0-alpine
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9093:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local

### Environment

- APISIX version (run `apisix version`): apisix:2.13.0-alpine
- Operating system (run `uname -a`): "CentOS Linux 7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): etcd:3.4.15
- APISIX Dashboard version, if relevant: 2.10.1-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

image: apache/apisix-dashboard:2.10.1-alpine
image: apache/apisix:2.13.0-alpine
image: bitnami/etcd:3.4.15

**Comment by tzssangglass** [comment]
pls check and increase the `ulimit`

**Comment by RexHuang** [comment]
systemctl restart docker.socket can solve the probelm.
Thanks tzssangglass any way.
