### ISSUE TITLE
apisix配置grafana地址

### ISSUE THREAD

**Issue by xuheavyrain** [apache/apisix-docker#329]

**Comment by tokers** [comment]
@xuheavyrain Could you provide more details?

**Comment by Chever-John** [comment]
Hi, I will solve it~

**Comment by xiaolei000129** [comment]
我使用了apisix-docker\example 中docker-compose.yml 部署apisix
apisix-docker\example\dashboard_conf\conf.yaml 

![image](https://user-images.githubusercontent.com/44334120/189848435-c695de63-2ba0-463d-882c-1f3b03f17730.png)

![image](https://user-images.githubusercontent.com/44334120/189848531-701eab6f-0238-4c18-8894-538924f235c8.png)

**Comment by Chever-John** [comment]
@xiaolei000129 I don't think that's the way I've configured it.

**Comment by Chever-John** [comment]
@xiaolei000129 You can try this [method](https://github.com/apache/apisix-docker/pull/340).

**Comment by Chever-John** [comment]
Terrible~
