### ISSUE TITLE
error code 404 but sometimes 200

### ISSUE THREAD

**Issue by rizkyarmanto** [apache/apisix-docker#334]
i fetch data from api but get error code 404 but sometimes 200

![image](https://user-images.githubusercontent.com/89382138/179458124-d074b75b-b70b-452b-9dbc-9520ff58d232.png)
![image](https://user-images.githubusercontent.com/89382138/179458136-282f9d46-3253-4dda-8e87-c3854a027517.png)

any suggestions to solve the problem?

**Comment by lilien1010** [comment]
@rizkyarmanto  you need elaborate more details to allow people to help you solve the issue
