### ISSUE TITLE
help request: centos dockerfile

### ISSUE THREAD

**Issue by stubbornTanzhe** [apache/apisix-docker#341]
is there a dockerfile which can build from source on centos?

**Comment by spacewander** [comment]
You can create one based on https://github.com/apache/apisix-docker/blob/master/centos/Dockerfile. Install your dependencies and mount your own code.

**Comment by stubbornTanzhe** [comment]
@spacewander apache-apisix-repo-1.0-1.noarch.rpm build dependencies and detail is under the hood, it's better the community can have a dockerfile which build from source on centos,so developers and track the dockerfile for updates and for long term

**Comment by spacewander** [comment]
The problem is that we have to maintain the same build process between apisix-build-tool & apisix-docker, which is troublesome...
