### ISSUE TITLE
help: 通过控制台配置了SNI后，java请求失败。

### ISSUE THREAD

**Issue by cnn007** [apache/apisix-docker#348]
证书：https://apisix.apache.org/zh/docs/apisix/certificate/

SSL证书申请于阿里云的免费证书。

1.通过Apache APISIX Dashboard 配置SSL，还需要 nginx 配置其它内容吗，例如 https 协议的版本兼容性，哪里配置。
![image](https://user-images.githubusercontent.com/13449400/188537251-e0cf6df1-5416-4db5-9e44-309e2a2b6f56.png)

2.通过java访问失败

请求代码如下, 请求百度都是正常，但是改为自己的域名，就失败。
`java`
public static void main(String[] args) {
        // 改成自己的就报错。
        String result = HttpUtil.get("https://www.myxxxx.com");
//      String result = HttpUtil.get("https://www.baidu.com");
        System.out.println(result);
    }

2.1 失败案例： 
jdk 版本：/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk
http工具：hutool-http 5.6.5
错误信息：
![image](https://user-images.githubusercontent.com/13449400/188534520-670afeeb-38ff-4b78-b879-7f7841a4bd35.png)

失败日志 error.log
`2022/09/06 10:51:20 [error] 45#45: *1613407 [lua] init.lua:172: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: xxxxxx, server: 0.0.0.0:9443`

2.2 成功案例：
jdk：/Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk
http工具：hutool-http 5.6.5
返回信息：
![image](https://user-images.githubusercontent.com/13449400/188534432-da45dc7d-f6c1-4ce2-9fe2-0143a2649d2d.png)

3.通过 curl ，nodejs，golang 语言测试可以正常。

**Comment by cnn007** [comment]
https://github.com/apache/apisix/issues/3037
https://github.com/apache/apisix/issues/4394

**Comment by soulbird** [comment]
It looks like you didn't bring SNI when you visited, java may need to set an option to enable

**Comment by cnn007** [comment]
> It looks like you didn't bring SNI when you visited, java may need to set an option to enable
参考资料：
https://github.com/dromara/hutool/issues/1573  
两种解决方法
方式1.升级jdk，
方式2.使用
 <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.13</version>
        </dependency>

`
// test ok
    private static void testPost() throws Exception {
        Map<String, Object> body = new HashMap<>();
        body.put("param1", "xxx");
        body.put("param2", "xxx");
        String url = "https://xxx:4443/index.html";

        // httpclient
        HttpPost httppost = new HttpPost(url);
//        httppost.addHeader("Content-type", "application/json");
        StringEntity entity = new StringEntity(JSON.toJSONString(body));
        httppost.setEntity(entity);
        HttpClient httpclient = HttpClients.createDefault();
        HttpResponse resp = httpclient.execute(httppost);
        HttpEntity he = resp.getEntity();
        String respContent = EntityUtils.toString(he, "UTF-8");
        System.out.println(respContent);
    }
`
