### ISSUE TITLE
help：配置log-rotate后，重启服务无数据

### ISSUE THREAD

**Issue by cnn007** [apache/apisix-docker#351]
1.看官方示例 log-rotate 是禁用，是不建议使用吗？
2.配置了 log-rotate 后，
没有修改 config.default ,修改 的是  config.yaml 文件，见下图：
![image](https://user-images.githubusercontent.com/13449400/189250887-82c9e1fa-6b87-47c1-9b07-cd814186830f.png)

保存退出，docker-compose restart 后，提示没有系统信息见下图：
![image](https://user-images.githubusercontent.com/13449400/189250956-ee3c8e5c-80b7-45d3-a74c-f1b4dd57cfad.png)
同时 grafana 也没有数据
![image](https://user-images.githubusercontent.com/13449400/189251269-8849354a-dfe0-4600-b29f-72f11c408620.png)

3.我看了 config.default 文件，是有 server-info 的配置。
![image](https://user-images.githubusercontent.com/13449400/189251192-6fffea9e-45fb-4ff7-bc93-6f5709d86b25.png)

**Comment by tokers** [comment]
@cnn007 When you specify `plugins` field in `config.yaml` it will override the `plugins` field in the `config-default.yaml`. So you only enable the `log-rotate` plugin. You need to specify all plugins you need in `config.yaml`.

**Comment by cnn007** [comment]
> @cnn007 When you specify `plugins` field in `config.yaml` it will override the `plugins` field in the `config-default.yaml`. So you only enable the `log-rotate` plugin. You need to specify all plugins you need in `config.yaml`.

那理解错了，以为配置文件会合并使用，就像springboot的 properties文件。这里是需要复制整个节点的全部内容。
