### ISSUE TITLE
apisix dashboard Grafana Access errors

### ISSUE THREAD

**Issue by xiaolei000129** [apache/apisix-docker#354]
I use the apisix-docker\example\docker-compose.yml deploy apisix
apisix-docker\example\dashboard_conf\conf.yaml

![image](https://user-images.githubusercontent.com/44334120/189849288-63659f36-5ce8-40b5-a8e4-cf961d881532.png)

Access http://127.0.0.1:9000/dashboard Grafana Access errors

![image](https://user-images.githubusercontent.com/44334120/189849380-a2c0251c-8cce-48b8-b3fa-c8e271772b84.png)

**Comment by tokers** [comment]
cc @bzp2010

**Comment by Chever-John** [comment]
csp rule problem.
you can refer to this [PR](https://github.com/apache/apisix-docker/pull/340).
