### ISSUE TITLE
Avoid affecting latest image when pushing a LTS image

### ISSUE THREAD

**Issue by spacewander** [apache/apisix-docker#362]
Currently, triggering an image push action in the CI will always push the image as the latest image if the type of the image is Debian.

This will bring us trouble if we are going to release an LTS image. We need to have a mechanism to distinguish these two kinds of images. For example, we can check the patch version number when pushing the latest image.

**Comment by tokers** [comment]
So, we need to know which versions are LTS in this repo?

**Comment by spacewander** [comment]
We don't need to know LTS. We just need to filter out all the patch releases.

**Comment by tokers** [comment]
> We don't need to know LTS. We just need to filter out all the patch releases.

Got it. Distinguish the patch part in the semantic version?

**Comment by spacewander** [comment]
Yes

**Comment by Hazel6869** [comment]
good job !

**Comment by tokers** [comment]
@Hazel6869 Would you like to do this? Thanks!
