### ISSUE TITLE
manifest for apache/apisix:2.99.0-alpine not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by galaxy-sea** [apache/apisix-docker#369]
```shell
~ % docker-compose -p docker-apisix -f docker-compose-arm64.yml up -d
Pulling apisix (apache/apisix:2.99.0-alpine)...
ERROR: manifest for apache/apisix:2.99.0-alpine not found: manifest unknown: manifest unknown
```

![image](https://user-images.githubusercontent.com/30821411/195476930-259a3ea2-fb02-4586-a85d-e52c4456da27.png)

**Comment by soulbird** [comment]
We will no longer maintain alpine images, please use `debian` or `centos` images. 
Also, can you submit a PR to fix the `docker-compose-arm64.yml` file ?

**Comment by galaxy-sea** [comment]
I have submitted [pr](https://github.com/apache/apisix-docker/pull/370)
