### ISSUE TITLE
Issue starting apisix using docker compose

### ISSUE THREAD

**Issue by sreeraksha** [apache/apisix-docker#374]
I have started the docker using docker compose but its failing to start. I was able to start it initially and was able to configure routes but I believe this issue started after I executed docker-compose -p docker-apisix down and then tried starting it. Please guide me.

Below i have highlighted the error logs of container that failed to start

<img width="938" alt="image" src="https://user-images.githubusercontent.com/30264507/200557513-53b8286f-a594-4e02-ac7a-4af254030093.png">

**Comment by shenzhuangzhi1** [comment]
cant connect to etcd.your should check the health of etcd
