### ISSUE TITLE
Remove separate section for APISIX Docker docs

### ISSUE THREAD

**Issue by navendu-pottekkat** [apache/apisix-docker#381]
Currently, the APISIX website has an Apache APISIX Docker subsection of documentation. This is unnecessary as all the documentation mentioned on the page could be moved to APISIX documentation.

This could make it easier to discover docs as they will be within the APISIX docs.

Related issue: https://github.com/apache/apisix-helm-chart/issues/394

**Comment by juzhiyuan** [comment]
Hi, I have checked both https://github.com/apache/apisix-docker/issues/381 and https://github.com/apache/apisix-helm-chart/issues/394.

No matter Helm or Docker, they belong to the way to install the software, so I agree to move them to each project's documentation 😊

**Comment by tokers** [comment]
+1

**Comment by navendu-pottekkat** [comment]
@juzhiyuan @tokers Looking through the current documentation, I think we can move everything in the APISIX Docker section to the README of this repository. We can have this README on the Docker Hub page.

General documentation regarding using APISIX docker images is available on the APISIX docs.

So, the README of this repository should be updated to include the details needed to work with this repository to create Docker images and how to use the Docker images.

If this seems okay, I will make a draft PR.

I can't seem to figure out where the documentation for this is coming from: https://hub.docker.com/r/apache/apisix-dashboard

I assumed that the README on Docker Hub was just a copy of the GitHub README, but this is not the same. Where is it coming from?

**Comment by juzhiyuan** [comment]
Hi @navendu-pottekkat,

> I assumed that the README on Docker Hub was just a copy of the GitHub README, but this is not the same. Where is it coming from?

We have one internal DockerHub account, as PMC member, I can share the access with you to update them.

> If this seems okay, I will make a draft PR.

LGTM 🙏

**Comment by Neilblaze** [comment]
@navendu-pottekkat If it's up for grabs, please assign me so that I can take a shot at it. I'll communicate over Slack as I move forward.

**Comment by navendu-pottekkat** [comment]
@Neilblaze This issue is already being worked on. I forgot to assign after picking up the issue.
