### ISSUE TITLE
etcd connection refused

### ISSUE THREAD

**Issue by inkeil** [apache/apisix-docker#383]
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused
all etcd nodes are unavailable

**Comment by soulbird** [comment]
Please provide at least the following information:
1. What is the version of APISIX?
2. The etcd configuration block in the configuration file

**Comment by huanghuanghui** [comment]
I have some problem. 
when I installing APISIX use docker.typing 
`git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example
docker-compose -p docker-apisix up -d
`
my docker ps 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/32832946/202975101-ddb85c00-13bb-4f20-849a-e74dcff455bc.png">

docker logs
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/32832946/202975235-6f9409d0-e9d7-4860-b35e-30a01423adc9.png">

my docker version
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/32832946/202975284-5e5f2f75-7294-4f50-a593-94997c884e55.png">

curl etcd on correct
 
<img width="935" alt="image" src="https://user-images.githubusercontent.com/32832946/202975410-23358488-be3a-43fe-9ee0-6fcb69679503.png">

**Comment by soulbird** [comment]
Please update the `apache/apisix:latest` image, the latest image id is `4be866d5e4bf`

**Comment by huanghuanghui** [comment]
> Please update the `apache/apisix:latest` image, the latest image id is `4be866d5e4bf`

thanks.I fix this problem when i change my docker registry-mirrors to https://registry-1.docker.io.I original use aliyun mirros.
before：
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/32832946/202977974-78811046-499b-4eaf-9db4-8e446403590d.png">
after：
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/32832946/202978201-36c5fea5-a4e8-4762-a639-ba1394501c80.png">

**Comment by jesse996** [comment]
same issue,but in apisix-dashboadr,version:2.13.1-alpine.  it's ok on 2.13-alpine

**Comment by vartruexuan** [comment]
> same issue,but in apisix-dashboadr,version:2.13.1-alpine. it's ok on 2.13-alpine
I have the same problem

**Comment by sunnyfrank** [comment]
same issue,but in apisix-dashboadr,version:2.15.0-alpine. apisix 2.15.0-alpine
I have the same problem, why the demo is not ok? i am so sad

**Comment by kneckinator** [comment]
Same issue here. Followed the instructions on [Install Apache APISIX](https://apisix.apache.org/docs/apisix/getting-started/#install-apache-apisix) for ARM/M1, getting this in the `apache/apisix-dashboard:2.15.0-alpine` container:
```
docker-apisix-apisix-dashboard-1  | {"level":"warn","ts":"2022-12-22T04:03:22.143Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000341a40/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused\""}
```

Also noting that the `rancher/coreos-etcd:v3.4.15-arm64` image is running under AMD64 emulation according to Docker. Is this expected?

The output of the `curl` test command `curl "http://127.0.0.1:9180/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'` is

```
{"total":0,"list":[]}
```

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/209533997-5d9675b7-c600-4e73-ba37-90b9516e10de.png)
same issue

**Comment by freemankevin** [comment]
```shell
docker pull apache/apisix:latest@sha256:4be866d5e4bf36eaa074c4e073661bf83d4cafc72c38cac34fc00761d340d9cb
docker tag b35c89de0dc6 apache/apisix:latest
docker-compose up -d
```
problem solved.
![image](https://user-images.githubusercontent.com/71524776/209534667-4d7279ec-5e6e-46b8-88ae-7e039a8f85a5.png)

**Comment by tokers** [comment]
> Same issue here. Followed the instructions on [Install Apache APISIX](https://apisix.apache.org/docs/apisix/getting-started/#install-apache-apisix) for ARM/M1, getting this in the `apache/apisix-dashboard:2.15.0-alpine` container:
> 
> ```
> docker-apisix-apisix-dashboard-1  | {"level":"warn","ts":"2022-12-22T04:03:22.143Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000341a40/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused\""}
> ```
> 
> Also noting that the `rancher/coreos-etcd:v3.4.15-arm64` image is running under AMD64 emulation according to Docker. Is this expected?
> 
> The output of the `curl` test command `curl "http://127.0.0.1:9180/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'` is
> 
> ```
> {"total":0,"list":[]}
> ```

It looks like the dashboard is not running normally, could you paste the apisix-dashboard configuration in the container?

**Comment by Carbin007** [comment]
> > Same issue here. Followed the instructions on [Install Apache APISIX](https://apisix.apache.org/docs/apisix/getting-started/#install-apache-apisix) for ARM/M1, getting this in the `apache/apisix-dashboard:2.15.0-alpine` container:
> > ```
> > docker-apisix-apisix-dashboard-1  | {"level":"warn","ts":"2022-12-22T04:03:22.143Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000341a40/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused\""}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also noting that the `rancher/coreos-etcd:v3.4.15-arm64` image is running under AMD64 emulation according to Docker. Is this expected?
> > The output of the `curl` test command `curl "http://127.0.0.1:9180/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'` is
> > ```
> > {"total":0,"list":[]}
> > ```
> 
> It looks like the dashboard is not running normally, could you paste the apisix-dashboard configuration in the container?

same issue in apisix-dashboard, version is 2.15.0-alpine, but in apisix, it works well and haven't the issue. The attachment is dashboard log in docker and the dashboard configuration.
![1674655295777](https://user-images.githubusercontent.com/6970894/214583498-8871c590-8ae4-4c36-9fb2-6c27ed5222b7.png)
[error.log](https://github.com/apache/apisix-docker/files/10499987/error.log)
[conf.yaml.txt](https://github.com/apache/apisix-docker/files/10499995/conf.yaml.txt)

**Comment by tokers** [comment]
It may relate to https://github.com/apache/apisix-docker/pull/412.

**Comment by bugoverflow-fix** [comment]
> ```shell
> docker pull apache/apisix:latest@sha256:4be866d5e4bf36eaa074c4e073661bf83d4cafc72c38cac34fc00761d340d9cb
> docker tag b35c89de0dc6 apache/apisix:latest
> docker-compose up -d
> ```
> 
> problem solved. ![image](https://user-images.githubusercontent.com/71524776/209534667-4d7279ec-5e6e-46b8-88ae-7e039a8f85a5.png)

Hello wants to know how to solve the problem of etcd communication?

**Comment by Carbin007** [comment]
> It may relate to #412.

Not sure. My issue occurs in the dashboard, I also see the some config about etcd in dashboard conf. and my config in apisit is updated with latest version. etcd config is under deployment
