### ISSUE TITLE
error occurs when the image is executed[apisix 2.14 update to 3.0.0]

### ISSUE THREAD

**Issue by ffch** [apache/apisix-docker#391]
I use the following dockerfile：
`https://github.com/apache/apisix-docker/blob/master/alpine/Dockerfile`

error info:
`2022/12/14 10:07:24 [emerg] 80#80: failed to init engine: Error relocating /usr/local/openresty/libgrpc_engine.so: (null): initial-exec TLS resolves to dynamic definition in /usr/local/openresty/libgrpc_engine.so with /usr/local/openresty/libgrpc_engine.so`

Is there any way to debug it next?

**Comment by spacewander** [comment]
We can remove the alpine dockerfiles now, as we don't maintain alpine environment anymore and they are already broken.
@soulbird 
What do you think?

**Comment by spacewander** [comment]
Now we only provide debian & centos image for 3.0.0.
See https://hub.docker.com/r/apache/apisix/tags
