### ISSUE TITLE
data not found    http://ip:port/apisix/admin/global_rules/1  

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix-docker#398]
{"code":10001,"message":"data not found","data":null,"request_id":"63a20d5c-af8e-446a-a5b3-a45f8c83faad"}

why？ 
services  version:
1.apache/apisix-dashboard:2.15.0-alpine
2.apache/apisix:latest
3.bitnami/etcd:3.4.15

**Comment by tokers** [comment]
Did you create such global rule and the ID is `1`?

**Comment by githubxubin** [comment]
i find the interface from official website&nbsp; with the param is 1 to query the global_rules . so i  think it's a fixed parameter.

Isn't it?  i need your help. thanks!







胥斌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix-docker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix-docker] data not found    http://ip:port/apisix/admin/global_rules/1   (Issue #398)





 
Did you create such global rule and the ID is 1?

**Comment by tokers** [comment]
See this for more details: https://apisix.apache.org/docs/apisix/terminology/global-rule/.

Data won't appear out of thin air. You need to create it first.
