### ISSUE TITLE
Discuss: unable to pull arm64 etcd image correctly on M1 arm arch

### ISSUE THREAD

**Issue by incubator4** [apache/apisix-docker#409]
This issue is to discuss how to correctly pull arm64 etcd image.
The problem might be caused  had been reported in issue #408 

### new problem about image `rancher/coreos-etcd`

Cause of [rancher/coreos-etcd:v3.4.15-arm64](https://hub.docker.com/layers/rancher/coreos-etcd/v3.4.15-arm64/images/sha256-0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464?context=explore) only has `amd64` arch, I tried [rancher/v3.4.15-rancher1](https://hub.docker.com/layers/rancher/coreos-etcd/v3.4.15-rancher1/images/sha256-0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464?context=explore) which has both `amd64` and `arm64` images, but got very subtle results.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/26524777/212616064-8e1fab8d-c645-4b6f-88fe-39c20972a2c7.png">

This shows that arm64 image hash is `sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464`.

Then I pull this image with `linux/arm64` arch.
```bash
$ docker pull --platform=linux/arm64  rancher/coreos-etcd:v3.4.15-rancher1

v3.4.15-rancher1: Pulling from rancher/coreos-etcd
Digest: sha256:bad82d2e064e81161db2d268a9e7c9c64bd8624a593c218556fe9d11ee0f3fc4
Status: Image is up to date for rancher/coreos-etcd:v3.4.15-rancher1
docker.io/rancher/coreos-etcd:v3.4.15-rancher1

$ docker inspect rancher/coreos-etcd:v3.4.15-rancher1 | jq '.[].Architecture'
"amd64"

docker inspect rancher/coreos-etcd:v3.4.15-rancher1 | jq '.[].Id'
"sha256:955737183a8fa5862209f31fe59d78aecc45682cca58f172013a87e58cc284f4"
```

And I tried pull image with hash.
```bash
$ docker pull --platform=linux/arm64  rancher/coreos-etcd:v3.4.15-rancher1@sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464
docker.io/rancher/coreos-etcd@sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464: Pulling from rancher/coreos-etcd
Digest: sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464
Status: Image is up to date for rancher/coreos-etcd@sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464
docker.io/rancher/coreos-etcd:v3.4.15-rancher1@sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464

$ docker inspect rancher/coreos-etcd:v3.4.15-rancher1@sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464 | jq '.[].Architecture'
"amd64"

$ docker inspect rancher/coreos-etcd:v3.4.15-rancher1@sha256:0725bee729805b5f2ba0c9213db884e22b64fd9a003a5414e254a98c278c3464 | jq '.[].Id'
"sha256:955737183a8fa5862209f31fe59d78aecc45682cca58f172013a87e58cc284f4"
```

The following are the results of my search
- https://github.com/docker/for-mac/issues/5625
- https://github.com/docker/hub-feedback/issues/1925

My conclusion is that it may be due to the following
- Docker Hub UI
- Moby platform feature error

Since this image was uploaded two years ago, I tested multiple etcd images on docker hub, which will be mentioned in the next reply.

**Comment by shivahnshankar** [comment]
I even tried `pachyderm/etcd` and `docker/desktop-kubernetes-etcd`. The etcd service starts but the dashboard fails to connect to the service. 
I am exploring whether this is the issue: [https://github.com/etcd-io/etcd/issues/10677#issuecomment-660935539](https://github.com/etcd-io/etcd/issues/10677#issuecomment-660935539) in etcd_data mount
