### ISSUE TITLE
Possible fix in entrypoint.sh - hardcoded path

### ISSUE THREAD

**Issue by sbrouet** [apache/apisix-docker#410]
Hello Team,

In entrypoint.sh for debian, at line 43 the path to configuration directory is hardcoded to `/usr/local/apisix`

See https://github.com/apache/apisix-docker/blob/master/debian/docker-entrypoint.sh#L43
```
exec /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'
```

But configuration directory can be configured with variable PREFIX which is declared at beginning of script and used for some commands, for initializing configuration:
```
PREFIX=${APISIX_PREFIX:=/usr/local/apisix}
[...]
cat > ${PREFIX}/conf/config.yaml << _EOC_
[...]
cat > ${PREFIX}/conf/apisix.yaml << _EOC_
```

-> It seems to me that variable should be used also in exec command show above, which would look like:
```
exec /usr/local/openresty/bin/openresty -p ${PREFIX} -g 'daemon off;'
```

If change is needed, must be done in all `docker-entrypoint.sh` files in Git repository.

Thank you,
Sébastien

**Comment by tokers** [comment]
@sbrouet Thanks! It's really useful!
