### ISSUE TITLE
Not same user (root VS apisix) used depending on Linux distribution

### ISSUE THREAD

**Issue by sbrouet** [apache/apisix-docker#411]
Hello Team,

I noticed that for some Docker images, the `root`  user is used, such as `centos`.
For others the `apisix` user is used, such as for `debian`.
This could lead to different behavior since user rights are different, so something that would work in `centos` Docker image would fail in `debian` one.

-> Suggestion: use applicative `apisix` in all Docker images and same user rights on directories

Thank you,
Sébastien

**Comment by soulbird** [comment]
@Hazel6869 please take a look

**Comment by Hazel6869** [comment]
> @Hazel6869 please take a look

ok

**Comment by Hazel6869** [comment]
> @Hazel6869请看一下  

Some users have this requirement, and modified the user permissions specifically for debian.  What do you think about this phenomenon of inconsistent permissions?  https://github.com/apache/apisix-docker/issues/326

**Comment by tokers** [comment]
> @soulbird Some users have this requirement, and modified the user permissions specifically for debian. What do you think about this phenomenon of inconsistent permissions? #326

In which case users need the root permission?

**Comment by soulbird** [comment]
I think all mirrors should behave the same. They should use the same user
