### ISSUE TITLE
路由配置中关闭插件无法生效

### ISSUE THREAD

**Issue by zhangxin-github** [apache/apisix-docker#415]
`{
  "uri": "/index.html",
  "name": "web1",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "plugins": {
    "hmac-auth": {
      "disable": true
    },
    "proxy-rewrite": {
      "uri": "/web1"
    }
  },
  "upstream_id": "445336888039965385",
  "labels": {
    "API_VERSION": "v1"
  },
  "status": 1
}`

在路由配置中已经关闭了hamc插件，但是请求时还是会调用hmac:

`2023/01/29 07:24:22 [warn] 55#55: *744503 [lua] hmac-auth.lua:430: phase_func(): client request can't be validated: access key or signature missing, client: 172.24.0.1, server: _, request: "GET /index.html?name=james&age=36 HTTP/1.1", host: "192.168.10.1:9080"
2023/01/29 07:24:22 [warn] 55#55: *744503 [lua] plugin.lua:1098: run_plugin(): hmac-auth exits with http status code 401, client: 172.24.0.1, server: _, request: "GET /index.html?name=james&age=36 HTTP/1.1", host: "192.168.10.1:9080"`

**Comment by tokers** [comment]
The information you provided is not sufficient. Please let us know:
1.  the APISIX version number;
2. how did you configure the route, plugin and disable the plugin
3. How did you reproduce the case

**Comment by zhangxin-github** [comment]
Thank you. Sorry, English is not good. Please allow me to use Chinese。

1.通过https://github.com/apache/apisix-docker.git获取最新版本，上传example目录到服务器，通过docker-compose up运行。
2.通过http://192.168.10.1:9000/dashboard控制台界面操作，创建了上游http://192.168.10.1:9081/web1，并配置了路由，在没有启用插件时，可以通过http://192.168.10.1:9080/api/web1正常访问路由配置正常。
3.在路由配置界面先启用hmac插件后再关闭插件，访问http://192.168.10.1:9080/api/web1，就会出现上面的日志发现hamc插件仍作用。

**Comment by tokers** [comment]
@bzp2010 Is this due to the incompatibility between APISIX and dashboard?

**Comment by zhangxin-github** [comment]
有没有大佬可以回答下啊？到底是我使用的不对，还是程序有BUG？
