### ISSUE TITLE
when i start apisix the docker-apisix_apisix_1 service is always in resarting status after 3s

### ISSUE THREAD

**Issue by Mkee2019** [apache/apisix-docker#430]
![image](https://user-images.githubusercontent.com/48989245/218363741-2104f8f6-3ffb-45ef-b32e-a45b5c2d73db.png)

my version is 3.0.0 

i have change the listening port 9080 to 9088 but it do not work 

the logs say （98 address already in use）but no progress on this address

what's wrong with me

**Comment by tokers** [comment]
Did you see the `ss -ntlp` result? Checkout if the ports are occupied.

**Comment by Mkee2019** [comment]
![image](https://user-images.githubusercontent.com/48989245/218419811-7ee72d28-0d30-4211-a691-1d74ce2e5a79.png)
there were no progress on this port ，but my apisix is restarting
![image](https://user-images.githubusercontent.com/48989245/218420103-381f86cb-7be8-4480-8fdc-108b7a4856c1.png)
