### ISSUE TITLE
Unable to create Consumer

### ISSUE THREAD

**Issue by PhanPirang** [apache/apisix-docker#433]
### Issue description

I use apisix-dashboard via Docker. I've fetched the new json schema from Apisix, then replace in apisix-dashboard. There's an issue while creating consumer.

### Expected behavior

Consumer should be created because I can create consumer on First start up. However, error has occurred after replacing the new json schema from Apisix

### How to Reproduce

1. Run Apisix with Dashboard
2. Fetch json schema from Apisix
3. Replace that file in Dashboard
4. Create consumer

### Screenshots

![key-auth](https://user-images.githubusercontent.com/12493118/219299880-00a99a5f-85dc-436e-b5b9-ada6b0ed6f12.PNG)

### Environment

- apisix version (3.1.0):
- OS (Linux):
- OpenResty / Nginx version (1.21.4.1):
- etcd version (3.4.15):
- apisix-dashboard version, (3.0.0)
- Browser version (Chrome Version 109.0.5414.120)

**Comment by tokers** [comment]
@bzp2010 Could you take a look when you have time? Thanks!

**Comment by PhanPirang** [comment]
This issue still exists in APISIX v3.2.0
