### ISSUE TITLE
 Attempting next endpoint for pull after error: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by i138** [apache/apisix-docker#469]
I cant pull apahce/apisix:3.3.0-debian and apisix-dashboard 
docker logs like this:
# docker pull apache/apisix:3.3.0-debian
Error response from daemon: manifest for apache/apisix:3.3.0-debian not found
# tailf -f /var/log/messages
May 29 15:10:29 myai dockerd: time="2023-05-29T15:10:29.129736539+08:00" level=info msg="Attempting next endpoint for pull after error: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>403 Forbidden</title></head>\\r\\n<body>\\r\\n<center><h1>403 Forbidden</h1></center>\\r\\n<hr><center>openresty</center>\\r\\n</body>\\r\\n</html>\\r\\n\""

~~~~~~~~~~~
how can i do?

**Comment by leslie-tsang** [comment]
Make sure your network can connect to DockerHub properly as it appears to be a network issue. :)

**Comment by i138** [comment]
Thank you, yes, my network is ok, I can docker pull other images like the nginx/etcd/grafana/prometheus, but I cannot pull the images apisix:3.3.0-debian and apisix-dashboard:3.0.1-alpine .
Today, I logged in and tried to pull using the virtual machine in labs.play-with-docker.com, but it show this message:
Error response from daemon: manifest for apache/apisix:3.3.0-debina not found: manifest unknown: manifest unknown

**Comment by leslie-tsang** [comment]
Considered resolved due to lack of feedback. Feel free to reopen it if needed.
