### ISSUE TITLE
document link for standalone is broken

### ISSUE THREAD

**Issue by xtha** [apache/apisix-docker#474]
link is broken: `If you want to know more configuration examples, you can refer to [stand-alone](https://apisix.apache.org/docs/apisix/stand-alone).`

**Comment by hamidrezakhosroabadi** [comment]
According to these issues ( https://github.com/apache/apisix/issues/9647 & https://github.com/apache/apisix-website/issues/1613),
standalone mode doc was moved to this address: https://apisix.apache.org/docs/apisix/deployment-modes/#standalone

**Comment by lingsamuel** [comment]
I am going to close this, refer: https://github.com/apache/apisix-docker/pull/449
