### ISSUE TITLE
bug: (CI) APISIX docker image build failing for redhat ubi

### ISSUE THREAD

**Issue by Revolyssup** [apache/apisix-docker#480]
Ref: [Failed run](https://github.com/apache/apisix-docker/actions/runs/5397835548/jobs/9813767386?pr=478#step:3:903)
For redhat ubi base image,  apisix-3.3.0 is not found while downloading packages before running tests.

**Comment by Revolyssup** [comment]
https://github.com/apache/apisix-docker/pull/478#issuecomment-1624514572

**Comment by AlinsRan** [comment]
Fixed. 
I will close this issue.
![7c8fe426-828e-461e-b636-4c7c2848cd36](https://github.com/apache/apisix-docker/assets/79972061/517ab38f-069b-4fc6-8b0f-0dca35f486b5)
