### ISSUE TITLE
help request: Health check

### ISSUE THREAD

**Issue by devteam-tb** [apache/apisix-docker#488]
Hi, How i can access the control Api endpoints? I can't access the /v1/healthcheck endpoint it shows like a socket hang-up. how we can resolve it? 

![image](https://github.com/apache/apisix-docker/assets/128605174/a56f9098-efbe-467c-b42a-77c79bf1477d)

**Comment by shreemaan-abhishek** [comment]
It works just fine for me, do you have any error logs to share?
