### ISSUE TITLE
apisix dashboard port

### ISSUE THREAD

**Issue by satishviswanathan** [apache/apisix-docker#493]
I'm trying to run the apisix dashboard other than port 9000 but I couldn't get it running.

I had modified the following yml files and replaced 9000 with port 5000. 

https://github.com/apache/apisix-docker/blob/master/example/docker-compose.yml

https://github.com/apache/apisix-docker/blob/master/example/dashboard_conf/conf.yaml

Please let me know if I'm missing anything here.

**Comment by monkeyDluffy6017** [comment]
@shreemaan-abhishek please help to check this

**Comment by shreemaan-abhishek** [comment]
@satishviswanathan please share the complete config files.
