### ISSUE TITLE
Proposal: Remove centos7-based APISIX image

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix-docker#507]
Proposed to remove APISIX docker image release based on centos 7

Mainly based on the following reasons:

1. centos has been upstreamed and is no longer maintained.
2. The centos 7 official image in dockerhub can no longer pass the security scan of dockerhub, which is unacceptable in the eyes of an enterprise customer.
3. APISIX provides opportunities for the release of redhat ubi image: docker pull apache/apisix:3.5.0-redhat

But this does not mean to completely abandon centos7, it just wants to leave the security issues of the operating system to the users themselves.

1. APISIX will still provide rpm release based on centos7.
2. APISIx currently still provides compatibility testing for centos7, which is guaranteed by the CI of apache/APISIX.

**Comment by monkeyDluffy6017** [comment]
LGTM, centos is no longer maintained, we can't guarantee the security of the centos image

**Comment by shreemaan-abhishek** [comment]
fixed by #512
