### ISSUE TITLE
apisix-docker/example/docker-compose.yaml run apisix  Missing plugins

### ISSUE THREAD

**Issue by tangtj** [apache/apisix-docker#517]
Missing plugins, I used the example in docker-compose.yaml to run apisix (3.6.0) and I found that some plugins are missing relative to the 3.6.0 version, such as forward-auth. How should I use these plugins correctly

**Comment by monkeyDluffy6017** [comment]
Do you use dashboard to manager plugins?

**Comment by tangtj** [comment]
> Do you use dashboard to manager plugins?

i try dashboard and admin api , cant found  forward-auth

`
curl --location --request PATCH 'http://ip:port/apisix/admin/routes/486219574769877929/plugins' \
--header 'Content-Type: application/json' \
--header 'X-API-KEY:' \
--data-raw '    {"plugins": {
        "forward-auth": {
            "uri": "http://127.0.0.1:9080/auth",
            "request_headers": ["Authorization"],
            "upstream_headers": ["X-User-ID"],
            "client_headers": ["Location"]
        }
    }
    }'
`

resp 
`
{
    "error_msg": "unknown plugin [plugins]"
}
`

**Comment by monkeyDluffy6017** [comment]
From the resp, you should check your uri, it should be wrong

**Comment by tangtj** [comment]
`
{
        "forward-auth": {
            "uri": "http://127.0.0.1:9080/auth",
            "request_headers": ["Authorization"],
            "upstream_headers": ["X-User-ID"],
            "client_headers": ["Location"]
        }
    
    }
`

solver , thanks
