### ISSUE TITLE
Unable to build the container in local

### ISSUE THREAD

**Issue by SilentEntity** [apache/apisix-docker#528]
This problem occurs in `apisix-docker/blob/master/debian-dev/` local development or while building master.

There is an issue with openresty PATH in image `api7/apisix-runtime:dev`.

Is there an reason to move from `api7/apisix-base:dev` to `api7/apisix-runtime:dev` ?

Adding openrestry path in [Dockerfile](https://github.com/SilentEntity/apisix-docker/blob/master/debian-dev/Dockerfile) solves it.

Example:
```
FROM api7/apisix-runtime:dev AS build

ARG ENABLE_PROXY=false

ENV DEBIAN_FRONTEND noninteractive

ENV PATH=$PATH:/usr/local/openresty/bin
RUN set -x \
```

**Comment by luoluoyuyu** [comment]
Hi @SilentEntity 
I am working on this issue, @AlinsRan please assign it to me

**Comment by Vacant2333** [comment]
@AlinsRan looks like this issue was resolved now?

**Comment by AlinsRan** [comment]
The issue has been resolved, you can try to verify it.

**Comment by Vacant2333** [comment]
hello, i have verify this now, can with no problem. looks like we can close this issue now~
<img width="781" alt="image" src="https://github.com/apache/apisix-docker/assets/19872346/f9dc65fe-1d2c-46d2-8a68-52d773e39f42">
start from APISIX 3.8, we are going to use apisix-runtime to replace openresty @SilentEntity
