### ISSUE TITLE
bug: sed not suitable for docker if config.yaml is volume mounted

### ISSUE THREAD

**Issue by jingzhao-self** [apache/apisix-docker#529]
https://github.com/apache/apisix-docker/blob/f9b445f80fa31de1aef5fbe2ee173f9934251ea9/redhat/docker-entrypoint.sh#L35

vim config.yaml
```
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key_required: false
    allow_admin:
      - 0.0.0.0/0
```
chmod +x config.yaml
chown 636:636 config.yaml

docker run -d --name apache-apisix \
  -v "$PWD"/config.yaml:/usr/local/apisix/conf/config.yaml \
  -p 9080:9080 -p 9180:9180 \
  -e APISIX_STAND_ALONE=true \
  apache/apisix

sed: cannot rename /usr/local/apisix/conf/sed4Q83NO: Device or resource busy

suggest to:
way1: remove this kind of implicit configuration, document to wirte this way.
way2: change to write this way:    echo "$(sed 's/role: traditional/role: data_plane/g' config.yaml)" > config.yaml

**Comment by luoluoyuyu** [comment]
Hi @jingzhao-self 
I think your case is great，are you willing to finish this job.

**Comment by kayx23** [comment]
Can reproduce. Following.

**Comment by jingzhao-self** [comment]
> Hi @jingzhao-self I think your case is great，are you willing to finish this job.

OK, I will try this.

**Comment by AlinsRan** [comment]
PR #534  has been fixed, I will close this issue.
