### ISSUE TITLE
bug: error related to mounted `config.yaml` in standalone mode (3.8.0, 3.9.0)

### ISSUE THREAD

**Issue by kayx23** [apache/apisix-docker#541]
## Current State

With the new `3.8.0-debian` image, I was unable to access route defined in the `apisix.yaml`:

![standalone-not-working](https://github.com/apache/apisix-docker/assets/39619599/cb0a63b6-933e-46d8-af8b-b82dcbedaead)

Note that:

1. the problem goes away if I do not mount `config.yaml`. In other words, if I just mount `apisix.yaml` with a route config, I could access the route successfully.
2. **this was not an issue in `3.5.0`** (unable to test with `3.6.0` and `3.7.0` due to [sed error](https://github.com/apache/apisix-docker/issues/529)), so something may have changed. See screenshot below:

![350-no-issue](https://github.com/apache/apisix-docker/assets/39619599/5dfc5e25-3121-4dda-891b-f944eff7296c)

**Therefore, this looks like an error related to mounting `config.yaml`.**

## Logs

```
2024/01/16 14:11:04 [error] 35#35: *6 [lua] config_yaml.lua:211: failed to check item data of [routes] err:allOf 1 failed: value should match only one schema, but matches none ,val: {"priority":0,"status":1}, context: init_worker_by_lua*
2024/01/16 14:11:04 [warn] 39#39: *5 [lua] plugin.lua:255: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"syslog":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2024/01/16 14:11:04 [error] 38#38: *2 [lua] config_yaml.lua:211: failed to check item data of [routes] err:allOf 1 failed: value should match only one schema, but matches none ,val: {"priority":0,"status":1}, context: init_worker_by_lua*
2024/01/16 14:11:04 [warn] 41#41: *8 [lua] plugin.lua:255: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"syslog":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2024/01/16 14:11:04 [error] 39#39: *5 [lua] config_yaml.lua:211: failed to check item data of [routes] err:allOf 1 failed: value should match only one schema, but matches none ,val: {"priority":0,"status":1}, context: init_worker_by_lua*
2024/01/16 14:11:04 [error] 41#41: *8 [lua] config_yaml.lua:211: failed to check item data of [routes] err:allOf 1 failed: value should match only one schema, but matches none ,val: {"priority":0,"status":1}, context: init_worker_by_lua*
2024/01/16 14:11:04 [warn] 46#46: *9 [lua] plugin.lua:255: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"syslog":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2024/01/16 14:11:04 [error] 46#46: *9 [lua] config_yaml.lua:211: failed to check item data of [routes] err:allOf 1 failed: value should match only one schema, but matches none ,val: {"priority":0,"status":1}, context: init_worker_by_lua*
```

**Comment by kayx23** [comment]
issue still persists

**Comment by fvilla-netnix** [comment]
I've come up with a simple fix to bypass the issue.

When working with the Docker image I override the entrypoint with `bash` and set the command as `-c "/usr/bin/apisix init && exec /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'"`

This will start the gateway and forgo the entrypoint config file initialization.

**Comment by kayx23** [comment]
Thanks, will you be opening a PR?

**Comment by fvilla-netnix** [comment]
Yeah, sure. I can try that.

**Comment by fvilla-netnix** [comment]
I've opened the pull request (https://github.com/apache/apisix-docker/pull/547).
Hope we can fix it.

**Comment by Jacky-Law** [comment]
apache/apisix:3.9.0出现同样问题，volume配置文件没有效果

**Comment by kayx23** [comment]
yep, it's not fixed yet...

**Comment by kayx23** [comment]
Issue is still relevant

**Comment by moonming** [comment]
closed by https://github.com/apache/apisix-docker/pull/558
