### ISSUE TITLE
apache/apisix:3.8.0-debian is not available for ARM64

### ISSUE THREAD

**Issue by kedare** [apache/apisix-docker#544]
Hello

It looks like there is an issue with the `apache/apisix:3.8.0-debian` image, it's not available on ARM64 where `apache/apisix:3.7.0-debian` however works fine.

``` shell
❯ docker pull apache/apisix:3.8.0-debian
3.8.0-debian: Pulling from apache/apisix
no matching manifest for linux/arm64/v8 in the manifest list entries

❯ docker pull apache/apisix:3.7.0-debian
3.7.0-debian: Pulling from apache/apisix
ca426296fe92: Pull complete
38f1433a1eb5: Pull complete
82ae04377c2d: Pull complete
4f4fb700ef54: Pull complete
3e0af0ce929f: Pull complete
cf0c16f871e9: Pull complete
2c60b7a0255e: Pull complete
Digest: sha256:1ce734ead49170049937828ab56a54b2176603a54f2c2236ccd58fde73e5acad
Status: Downloaded newer image for apache/apisix:3.7.0-debian
docker.io/apache/apisix:3.7.0-debian
```

Thanks

**Comment by kedare** [comment]
Likely related to this failing job ?
https://github.com/apache/apisix-docker/actions/runs/7525652871/job/20482350035

**Comment by kedare** [comment]
Looks like it's already talking about it there : 
https://github.com/apache/apisix-helm-chart/issues/707

Should we keep an issue open here until this is fixed ? (as the build is done here and not there)

**Comment by monkeyDluffy6017** [comment]
It's better to submit this issue in the apisix repository

**Comment by kedare** [comment]
Are you sure ? I don't see much issues related to docker on the apisix repository compared to here where the build is being run.

Do you remember what was the issue with building the arm64 version ? I can probably take a look.

**Comment by AlinsRan** [comment]
The ARM image was released 18 days ago.
It was not deleted, but the release time was delayed due to the lack of deb arm package.

This issue can be closed now.
