### ISSUE TITLE
bug: apisix running on docker throwing 404

### ISSUE THREAD

**Issue by bsudhir6** [apache/apisix-docker#560]
I have pulled latest code from the repo and ran docker compose up from example directory. when tried call below command

`curl --location '127.0.0.1:9080/apisix/admin/services' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

it is throwing 404. but in videos from you tube it is returning some data. can you tell me what was wrong with my system?

I am running docker on windows.

see below screenshot:

![image](https://github.com/user-attachments/assets/0f61afe7-a82e-4f6d-9825-ff651fcf3753)

**Comment by bsudhir6** [comment]
![image](https://github.com/user-attachments/assets/400269d9-93fc-4399-b640-88103d23bc20)
see above response

**Comment by TheShubhendra** [comment]
https://apisix.apache.org/docs/apisix/admin-api/#configuration As mentioned here, by default Admin API listens on port 9180

**Comment by bsudhir6** [comment]
Thanks its working. Great. Thank you so much @TheShubhendra
