### ISSUE TITLE
gcr.azk8s.cn no longer public

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-docker#59]
Reference: https://github.com/Azure/container-service-for-azure-china/issues/58#issuecomment-630765201

**Comment by gxthrj** [comment]
the image has been changed, used `gcr.io/etcd-development/etcd:v3.3.12` now
https://github.com/apache/incubator-apisix-docker/blob/f3db8c3e3f6860ef32af2d4373ab864d1b55a178/example/docker-compose.yml#L25

**Comment by lingsamuel** [comment]
What's this?
https://github.com/apache/incubator-apisix-docker/blob/f3db8c3e3f6860ef32af2d4373ab864d1b55a178/example/docker-compose.yml#L23-L24
