### ISSUE TITLE
[Request HELP] docker: 安装

### ISSUE THREAD

**Issue by spjiang** [apache/apisix-docker#61]
按照官方docker文档部署：
https://github.com/apache/incubator-apisix-docker
现象：
运行地址：
http://127.0.0.1:9080/apisix/dashboard
返回：
{"error_msg":"failed to match any routes"} 
请问怎么排查问题？或是是什么原因导致的呢？

**Comment by moonming** [comment]
it's a bug, and will fixed by https://github.com/apache/incubator-apisix/issues/1794
