### ISSUE TITLE
bug: failed to start the apisix-1.5:alpine

### ISSUE THREAD

**Issue by membphis** [apache/apisix-docker#69]
run: apache/apisix:1.5-alpine 
error log: nginx: [emerg] invalid number of arguments in "worker_shutdown_timeout" directive in /usr/local/apisix/conf/ nginx.conf:21

**Comment by moonming** [comment]
@gxthrj please take a look.
Can we update this configuration automatically?

**Comment by moonming** [comment]
@gxthrj please add test cases in CI to check if this bug exist.

**Comment by gxthrj** [comment]
ok,get it

**Comment by to2false** [comment]
Any fix? Had same error now.

**Comment by moonming** [comment]
@gxthrj please take a look.

**Comment by gxthrj** [comment]
I think we can close this PR now , since we use  `config-default.yaml` to solve this kind of problems.
