### ISSUE TITLE
dashboard 首页文件404

### ISSUE THREAD

**Issue by zwjzxh520** [apache/apisix-docker#76]
- apisix version: master
- apisix-dashboard version: master

通过 http://localhost:9080/apisix/dashboard 访问时，发现js和css文件404

![image](https://user-images.githubusercontent.com/2184202/93566229-49c5f000-f9bf-11ea-88a6-9a692e76510d.png)

但是发现 http://localhost:9080/apisix/dashboard/umi.0874684c.js 这样请求js是能正常返回内容的

所以要怎么才能让首页返回的文件，自动带上 apisix/dashboard 路径呢？

**Comment by juzhiyuan** [comment]
Hi, please have a try on the latest codes.

https://github.com/apache/apisix-docker/tree/master/all-in-one
