### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by zsq1234** [apache/apisix-docker#77]
Hi~, I have an error I don't know how to deal.

my operation: 
1. docker run --rm -it apache/apisix:latest /bin/sh
2. apisix version / apisix init
then "Illegal instruction (core dumped)"

![core_dump](https://user-images.githubusercontent.com/41423998/93693611-b3b3d600-fb34-11ea-8cdb-6216932fca56.png)

**Comment by zsq1234** [comment]
I guess this problem maybe is also [openresty version use sse4.2](https://github.com/openresty/docker-openresty/issues/49) , I would be very grateful  if can also provide a [nosse42 version](https://github.com/openresty/docker-openresty/issues/103) , thanks ~

**Comment by membphis** [comment]
@zsq1234 any news about this issue?
