### ISSUE TITLE
apisix2.0 docker外部请求 403

### ISSUE THREAD

**Issue by zlchanger** [apache/apisix-docker#84]
我打算先把apisix升级到2.0，现在很明显docker内部已经是2.0了，但为什么内部可以访问，外面却访问不了，端口我已经映射出来了，而且config.yaml里面的allow_admin也被我直接注释掉了
![avatar](https://apollobucket.oss-cn-beijing.aliyuncs.com/error.png)

_Originally posted by @zlchanger in https://github.com/apache/apisix-dashboard/issues/663#issuecomment-720878123_

**Comment by membphis** [comment]
We need to update the default `conf/config.yaml`.
