### ISSUE TITLE
bug: host can not request APISIX docker

### ISSUE THREAD

**Issue by idbeta** [apache/apisix-docker#85]
403 error occurred when the host request APISIX docker.
because no matter /example/apisix_conf/config.yaml or config.yaml which created by gen-config-yaml.sh, there is no such configuration:
```
allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
   - 0.0.0.0/0
```
relate #84

**Comment by membphis** [comment]
welcome PR to fix this issue
