### ISSUE TITLE
Error: Could not load rockspec file /tmp/luarocks_luarocks-rockspec-apisix-master-0-kbdBgI/apisix-master-0.rockspec (Error loading file: [string "/tmp/luarocks_luarocks-rockspec-apisix-master..."]:7: unexpected symbol near '<')

### ISSUE THREAD

**Issue by jclivi** [apache/apisix-docker#88]
OK: 326 MiB in 81 packages
+ luarocks install https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec '--tree=/usr/local/apisix/deps'

Error: Could not load rockspec file /tmp/luarocks_luarocks-rockspec-apisix-master-0-kbdBgI/apisix-master-0.rockspec (Error loading file: [string "/tmp/luarocks_luarocks-rockspec-apisix-master..."]:7: unexpected symbol near '<')
ERROR: Service 'apisix' failed to build : The command '/bin/sh -c set -x     && /bin/sed -i 's,http://dl-cdn.alpinelinux.org,https://mirrors.aliyun.com,g' /etc/apk/repositories     && apk add --no-cache --virtual .builddeps     automake     autoconf     libtool     pkgconfig     cmake     git     && luarocks install https://github.com/apache/apisix/blob/master/rockspec/apisix-${APISIX_VERSION}-0.rockspec --tree=/usr/local/apisix/deps     && cp -v /usr/local/apisix/deps/lib/luarocks/rocks-5.1/apisix/${APISIX_VERSION}-0/bin/apisix /usr/bin/     && bin='#! /usr/local/openresty/luajit/bin/luajit\npackage.path = "/usr/local/apisix/?.lua;" .. package.path'     && sed -i "1s@.*@$bin@" /usr/bin/apisix     && mv /usr/local/apisix/deps/share/lua/5.1/apisix /usr/local/apisix     && apk del .builddeps build-base make unzip' returned a non-zero code: 1

**Comment by membphis** [comment]
this step is unstable in china: `luarocks install https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec`

**Comment by jclivi** [comment]
OK！Thank you！

**Comment by UnderTreeTech** [comment]
> this step is unstable in china: `luarocks install https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec`

Meet same issue, but it does not work using your suggestion.

**Comment by spacewander** [comment]
@UnderTreeTech 
Try it again? I always turn on the VPN when I need to use luarocks.
You may need to capture network to see what happened.

**Comment by UnderTreeTech** [comment]
I've already start global proxy, but it still comes the same issue.

**Comment by spacewander** [comment]
You can make a network capture to see what happened. BTW, it would be better to submit this issue to luarocks since we don't control the `luarocks.org`. There is few things we can do in our side.

**Comment by UnderTreeTech** [comment]
I don't think so, lua install execute right now. It's build error now.

**Comment by spacewander** [comment]
It is apparently that luarocks is downloading something which it expects to be JSON but HTML actually. We can't solve the problem if you don't provide a network capture file.
