### ISSUE TITLE
docker compose example start failed 

### ISSUE THREAD

**Issue by nooperpudd** [apache/apisix-docker#89]
`sh gen-config-yaml.sh && docker-compose -p docker-apisix up -d`

ERROR: for docker-apisix_apisix_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for apisix  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by moonming** [comment]
@gxthrj please take a look

**Comment by gxthrj** [comment]
@nooperpudd Would you please show me `docker ps`?
I  exec  `sh gen-config-yaml.sh && docker-compose -p docker-apisix up -d` in a new centos7 just now. Get success.
![image](https://user-images.githubusercontent.com/4413028/100338139-2d73ae80-3013-11eb-9f05-26395f865fcf.png)
