### ISSUE TITLE
Unable to start port 9443 in docker

### ISSUE THREAD

**Issue by qwxingzhe** [apache/apisix-docker#96]
### Issue description
It could be config.yaml Configuration does not enable SSL, when I open the following error

`missing ssl cert for ssl`

![image](https://user-images.githubusercontent.com/7071651/101561135-b91c1080-39ff-11eb-9389-2f6d4cd20ea8.png)

My configuration is as follows
![image](https://user-images.githubusercontent.com/7071651/101561231-ebc60900-39ff-11eb-97d2-13c4f6652a74.png)

Refer:  https://github.com/apache/apisix/blob/master/conf/config-default.yaml

### Environment
docker-compose.yml
~~~
version: "3"

services:
  apisix:
    image: apache/apisix:2.1-alpine
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
#      - "9080:9080/tcp"
#      - "9443:9443/tcp"
    networks:
      apisix:
        ipv4_address: 172.18.5.11

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:
        ipv4_address: 172.18.5.10
~~~

**Comment by qwxingzhe** [comment]
Maybe there is a mirror problem. When I replace it with `apache/apisix:2.1-alpine`, it runs

**Comment by tokers** [comment]
@qwxingzhe From the config.yaml snippet, the ssl is enabled but the cert and pkey are not provided.

**Comment by qwxingzhe** [comment]
> @qwxingzhe From the config.yaml snippet, the ssl is enabled but the cert and pkey are not provided.

Yes, but `apache/apisix:2.0-alpine` works. Maybe it's a version problem

**Comment by gxthrj** [comment]
It seems the `ssl_cert` and `ssl_cert_key` must be set  In APISIX 2.1 when ssl is enabled.
