### ISSUE TITLE
bug: when set `apisix.ssl.enable: true`, can not start APISIX with docker 2.1-alpine

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-docker#97]
### Environment

* apisix version : docker image apache/APISIX:2.1-alpine
* OS: 

### Minimal test code / Steps to reproduce the issue
1. set `apisix.ssl.enable: true` in `config.yaml`
![image](https://user-images.githubusercontent.com/4413028/101522018-9965f780-39c1-11eb-8247-c6b9e7e2e736.png)
2. the docker of APISIX start failed
![image](https://user-images.githubusercontent.com/4413028/101522063-b00c4e80-39c1-11eb-824e-434d63482b5b.png)

3. Then, I copy the `nginx_config` item into `config.yaml`, restart `APISIX`, failed and report as blow

![image](https://user-images.githubusercontent.com/4413028/101522318-01b4d900-39c2-11eb-801e-b7e4a0dc9b73.png)

**Comment by gxthrj** [comment]
related to #96

**Comment by gxthrj** [comment]
I think it is a bug in APISIX. Reproduce in steps:
1. Use [rpm](https://github.com/apache/apisix/releases/download/2.1/apisix-2.1-0.el7.noarch.rpm).
2. set `apisix.ssl.enable: true`.
3. apisix start
```sh
/usr/local/openresty/luajit/bin/luajit: /usr/bin/apisix:256: missing ssl cert for ssl
stack traceback:
	[C]: in function 'error'
	/usr/bin/apisix:256: in function 'init'
	/usr/bin/apisix:364: in function </usr/bin/apisix:349>
	/usr/bin/apisix:419: in main chunk
	[C]: at 0x00404c00
```

**Comment by gxthrj** [comment]
@membphis  @spacewander Please have a look if you have time.

**Comment by membphis** [comment]
need to specify the default SSL certificate, here is the link:

https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L103-L112

**Comment by moonming** [comment]
@gxthrj ping

**Comment by spacewander** [comment]
Look like we can close it since https://github.com/apache/apisix/pull/3013 is merged.

**Comment by gxthrj** [comment]
Yes， I will test in docker image from master / 2.1 / 2.0.

> Look like we can close it since [apache/apisix#3013](https://github.com/apache/apisix/pull/3013) is merged.

**Comment by gxthrj** [comment]
Close this issue now , it is the same reason with #106
